### ISSUE TITLE
Update dependencies for v2023.5

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#1006]

**Comment by lognaturel** [comment]
Make sure to upgrade `bcrypt` as described by @swoodcock at https://forum.getodk.org/t/bcrypt-dependency-install-fails-on-arm64-architectures/43992

I think we still want to keep control over the minor version to ensure consistency but could be convinced otherwise.

**Comment by matthew-white** [comment]
> I think we still want to keep control over the minor version to ensure consistency but could be convinced otherwise.

Just to clarify, are you thinking of the semver range specified in package.json? package-lock.json is what ensures consistency across installs. The semver range constrains what updates are possible when a dev runs `npm update`.

Relatedly, I noticed this statement in the forum post:

> It's currently pinned with a tilde `~5`, meaning the max version is `5.0.1`.

However, I'm pretty sure that `~5` includes any `5.x`.

**Comment by ktuite** [comment]
Ah yes I see what you mean about `5.x` ([npm docs](https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1)). I just updated bcypt within the `package-lock.json` file.
