### ISSUE TITLE
Get rid of `submissionCreate` from GET entities/:uuid/audits

### ISSUE THREAD

**Issue by sadiqkhoja** [getodk/central-backend#1036]
From https://github.com/getodk/central-backend/pull/1028#discussion_r1372523633

> ... how the submissionCreate property of the audit log details feels like it could be improved. Currently, submissionCreate is needed if the submission is deleted, because in that case, no submission property is returned, so submissionCreate is the only way to get basic information about the submission (e.g., instanceId). As an alternative, we could always return a submission property. (In the deleted case, maybe we construct submission using the submission.create event.) That'd work similarly to the entity property, which is always returned and includes basic information (e.g., uuid) even if the entity is deleted.

**Comment by matthew-white** [comment]
@ktuite and I chatted about this issue. We'd like to make this change at some point, but we probably won't get to it for v2023.5. However, we'll be touching entity sources again in v2024.1 as we work on bulk upload. I'll go ahead and bump this issue.

**Comment by ktuite** [comment]
Places to change code in backend
* audits for entities
* `getWithConflicDetails` (passes thru audit details)

Places to change code in frontend entity components:
* activity (code adds another event to show submission created if needed)
* basic details (shows the creating submission or nothing if created with api)
* feed entry
* version link

Ways `submissionCreate` is used
* to tell if entity was created with a submission or api
* get the instance id of the submission
* absence of `submission` and presence of `submissionCreate` indicates that submission was deleted

Plan
* move things from `submissionCreate` into submission property and always return `submission`
  * instance id 
  * creator and creation date (as full actor object)
  * easy way to tell if submission is deleted or not (maybe presence of `currentVersion`?)
