### ISSUE TITLE
API documentation inconsistencies

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#1118]
There are two API endpoints which are documented, but do not seem to correspond to real routes in code:

```
GET    /v1/test/:key/projects/:id/forms/:id/attachments/:name
PATCH  /v1/projects/:id/forms/:id/draft/submissions/:id/attachments/:name
```

cc @matthew-white

**Comment by matthew-white** [comment]
> ```
> GET    /v1/test/:key/projects/:id/forms/:id/attachments/:name
> ```

It looks like this should be .../**draft**/attachments/:name:

https://github.com/getodk/central-backend/blob/428ebdd06143684759f1507a708db69fd2f0b76c/lib/resources/forms.js#L441

> ```
> PATCH  /v1/projects/:id/forms/:id/draft/submissions/:id/attachments/:name
> ```

I'm pretty sure we only POST to submission attachment endpoints, not PATCH.

https://github.com/getodk/central-backend/blob/428ebdd06143684759f1507a708db69fd2f0b76c/lib/resources/submissions.js#L417-L418
https://github.com/getodk/central-backend/blob/428ebdd06143684759f1507a708db69fd2f0b76c/lib/resources/submissions.js#L523

**Comment by matthew-white** [comment]
> ```
> PATCH  /v1/projects/:id/forms/:id/draft/submissions/:id/attachments/:name
> ```

I'm actually not seeing this one in the docs anywhere. Maybe we fixed it already? @alxndrsn, let me know if I'm missing something and you still see it in the docs.
