### ISSUE TITLE
Timezone-sensitive test failures

### ISSUE THREAD

**Issue by brontolosone** [getodk/central-backend#1185]
```sh
BCRYPT=insecure npx mocha --recursive --exit --bail --grep 'should not mince( the)? object properties' 
```

fails (3 tests, 3 failures) if you have a timezone offset positive to UTC in your database connection (as many in the Eastern hemisphere are wont to have).

Eg
```
  1) Entities API
       GET /datasets/:name/entities
         should not mince the object properties:
     AssertionError: expected '2021-12-31T23:00:00.000Z' to match /2022/
```

It's an hour off, which around Newyear can make me a year off.
And I'm an hour off from UTC.

What's happening is with statements such as these:

```sql
UPDATE actors SET "createdAt" = '2020-01-01'
```
(where the `createdAt` column is of type `timestamptz`)
1. the string `'2020-01-01'` will suffer an attempted conversion to the column type `timestamptz`
2. for that, `'2020-01-01'` is interpreted as a date
3. but the column needs a timestamptz, and we didn't supply a time, so `00:00:00` is made up for the upcast
4. but we also didn't supply any timezone indication, so another thing needs to be made up for the upcast; PostgreSQL uses the connection's timezone setting (`SHOW timezone;`) for this. Mine's UTC+1 at the moment.
5. So we have `2020-01-01 00:00:00 UTC+1` but a `timestamptz` column stores UTC (yes! `timestamptz` does not store timezone information!) so that's converted to `2020-01-01 23:00:00 UTC`. That's what's stored (minus the timezone; it's discarded, as internally PostgreSQL knows that timestamptz columns store time in UTC).
6. Upon retrieval, that timestamptz value is converted to the timezone setting of the connection in which the SELECT runs (which may or may not be the same as the timezone setting from when it was stored - that's the whole point of timestamptz; to save you from having to do conversions yourself).
7. What happens further on once the value's read could be anything, it depends on the framework and the libraries and what people think is "right". So what made this '2021-12-31T23:00:00.000Z' show up in this form (UTC), I don't know :man_shrugging:, but regardless the presentation, what's *stored* is not what it should be.

Two possible solutions:
1. Don't be ambiguous, leave nothing to guess, and specify timestamptz's fully qualified.
2. Let PostgreSQL make up the missing information, but set the connection timezone to UTC.

I think 1. is the way to go, so that's what's done in PR https://github.com/getodk/central-backend/pull/1186.

**Comment by matthew-white** [comment]
(2) would be a smaller change in terms of the size of the diff, but I also don't have any issue with (1). @ktuite, do you have a preference between the two?

**Comment by matthew-white** [comment]
@ktuite mentioned during the meeting today that she was supportive of (1). I'll go ahead and review the PR!
