### ISSUE TITLE
Drop support for legacy tokens

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#1261]
If https://github.com/getodk/central-backend/pull/1234 is merged, newly-generated tokens will not contain `$` or `!` characters.  However, legacy tokens may exist in:

* sessions
* field keys
* enketo access tokens
* CSRF tokens

Once these tokens are sufficiently old enough or have been revoked or updated, remove support for them.

**Comment by matthew-white** [comment]
I'm actually not sure that this is something we should do. App users and public links can operate indefinitely without expiring. Given that, I don't think there will be a time when we feel certain that all app users and public links created before 2025 are done being used. I understand that it'd be nice not to mention `$` or `!` anywhere in the codebase. However, it's just one regular expression, which is commented. I don't think it'd be worth risking user disruption to remove these characters.

**Comment by lognaturel** [comment]
Agreed that this feels unlikely to be something we can ever do. Some projects are extremely long-running. I'd be in favor of closing this.
