### ISSUE TITLE
Two different `Option`s .should.not.eql each other

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#1296]
#1287 removes direct access to the `value` property of `Option` objects. That caused Ramda to consider all `Option`s to be equal, so the PR also added an `equals()` method to `Option`. However, I'm realizing that there's a similar issue with Should.js. Now that it doesn't have access to `value`, `eql()` (AKA `deepEqual()`) no longer throws for two different `Option`s. For example:

```js
// This passes.
Option.of(1).should.eql(Option.of(2));
```

We have tests with assertions like that. I noticed this issue while looking at #1291, where you can see this test:

https://github.com/getodk/central-backend/blob/ca1652e0f10ee6e500777c78c19a19d1f456ea5a/test/unit/http/middleware.js#L56-L63

If I change `Option.of('12|45')` to something else in the test, the test continues to pass.

It looks like Should.js still distinguishes between empty and non-empty `Option`s, since they have different prototypes.

Instead of using a private property like `#value` in `Option`, how about using something like `_value` or `Symbol('value')`? I think those would signal effectively that the property isn't meant to be used outside the class.

**Comment by alxndrsn** [comment]
I've tried to address this in https://github.com/getodk/central-backend/pull/1297
