### ISSUE TITLE
Github actions don't run on PRs from forks

### ISSUE THREAD

**Issue by lognaturel** [getodk/central-backend#1308]
A PR from @ktuite on this repo ran 7 checks including Github actions: https://github.com/getodk/central-backend/pull/1299/commits/2e76ed07fb65cf39237b71c0f7f8908f8e9676ee

A PR from @alxndrsn on his fork only ran the build step in CircleCI: https://github.com/getodk/central-backend/pull/1307/commits/54f10cec71cab98f7060a11a7efded0abe0cc2d6

Ideally all checks would run for forks of members of the organization and would require authorization for folks coming from outside the organization. That's how our other repos are set up.

**Comment by alxndrsn** [comment]
What's the concern here?

There are a few other things we should probably also be considering for actions security.  The default permissions seem quite permissive:

![Screenshot_2024-11-27_09-26-45](https://github.com/user-attachments/assets/b1ab399c-7c8f-4048-b96f-e41b8de85be2)

**Comment by alxndrsn** [comment]
Further reading: https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions

**Comment by alxndrsn** [comment]
I think this PR to restrict access to `GITHUB_TOKEN` from jobs would be helpful: 

https://github.com/getodk/central-backend/compare/master...alxndrsn:actions-minimal-permissions?expand=1

**Comment by lognaturel** [comment]
Made this as as a placeholder and hadn't had a chance to come back! The goal is for all checks including github actions to run for PRs made on the forks of contributors to the organization (e.g. @alxndrsn). Running checks for PRs from forks of contributors outside the org should require maintainer approval -- https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by alxndrsn** [comment]
> Made this as as a placeholder and hadn't had a chance to come back! The goal is for all checks including github actions to run for PRs made on the forks of contributors to the organization

:+1:

I would guess workflow configs should change something like the following:

```diff
-on: push
+on:
+  push:
+    branches: master
+  pull_request:
```

**Comment by alxndrsn** [comment]
Or

https://github.com/XLSForm/pyxform/blob/b65e7277d846780140449232db7ba3952324bc1b/.github/workflows/verify.yml#L3

cc @lognaturel

**Comment by lognaturel** [comment]
I think we'd like to run on all branches. Here's someone with the same issue: https://github.com/szabgab/github-actions-avoid-duplicate-trigger?tab=readme-ov-file They point to https://github.com/marketplace/actions/skip-duplicate-actions which seems reasonable.

There's also https://github.com/orgs/community/discussions/57827

Maybe take a quick look and see if either of those seems reliable and reasonable? If not, I think we just live with the double runs like we do with pyxform.
