### ISSUE TITLE
OData: add a service+metadata document at the project root

### ISSUE THREAD

**Issue by issa-tseng** [getodk/central-backend#203]
right now we have one OData service per form.
so for instance: `/v1/projects/1/forms/birds.svc` is a service document (a directory, essentially) which offers up at least a `Submissions` table (`/v1/projects/1/forms/birds.svc/Submissions`), plus whatever repeats are a part of the `birds` form.

it would be nice if we could allow `/v1/projects/1.svc` which lists all the tables for all the forms in the project as a whole. it would use the just form document urls (eg the `/Submissions` url listed above) for all the actual data.

xmlformid is guaranteed unique, so this should be safe to do.

the main headache is merging together all the entities for all the forms for the CSDL. it's not difficult, but it may be tedious.

**Comment by matthew-white** [comment]
Closing after discussion with @lognaturel. We can always reopen if we end up wanting to prioritize this change.
