### ISSUE TITLE
Characters used in tokens

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#264]
I'm wondering whether it'd be useful to update the set of characters that we use in the tokens that Backend generates. Right now I think the set is `A-Za-z0-9!$`. (`generateToken()` is [here](https://github.com/getodk/central-backend/blob/c9eb20eb8d9139b07938158008a7962a1f27047c/lib/util/crypto.js#L36-L39).)

Frontend assumes that Backend tokens are URL-friendly and don't need to be encoded, but I'm realizing now that `$` maybe should be encoded. (Maybe the answer here is just that I should start encoding these tokens in Frontend.)

I think @lognaturel and @yanokwa have also had trouble with tokens that contain `!`, since that's a special shell character.

Alternative characters might be `_`, `-`, and `.`. I'm pretty sure those characters don't need to be encoded in URL components or query parameters. And as far as I know, they also aren't special shell characters. (Though I guess `-` could indicate the start of a flag?)

**Comment by issa-tseng** [comment]
hmm. i chose those characters carefully to avoid the need for url encoding.

i understand the issues with the shell, though tbh my opinion is that all http-related values (urls, tokens, etc) are just generally scary enough that you should always wrap them in quotes regardless of how safe they seem. the tokens aren't the only things that will trip you up this way.

i don't have a huge issue with changing to `_` and `-` but i'd rather not touch it unless it's a really big deal.

**Comment by yanokwa** [comment]
I find the special characters mildly irritating. Besides the escaping thing, it also makes it hard to double-click to copy the token. Why not drop them and make token a little longer?

**Comment by issa-tseng** [comment]
well, `-` will also not work for double-click-to-copy.
i just base64-encode a securely-generated random key. i don't know how many of that character i'm going to get and i can't securely make it longer.

**Comment by matthew-white** [comment]
In terms of URL-encoding, I don't think we've heard of any issues, so it seems to be working the way it is. `$` does seems to be a reserved character though, as far as I can tell. (`encodeURIComponent('$')` returns `'%24'`.) For what it's worth, I've been encoding the `$top` and `$skip` OData query parameters.

MDN [seems to say](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) that `!` doesn't need to be encoded for URL path components, but should be encoded for query parameters (which apparently are governed by a slightly different, stricter spec). We pass a token as a query parameter as part of the account creation email, though that may be the only place we do so. We haven't heard of any issues with account creation though, so I'm guessing that most browsers know what to do with a query parameter that contains a `!`.

**Comment by issa-tseng** [comment]
here is the actual rfc:
https://www.ietf.org/rfc/rfc3986.txt
which in forever words says that this is the legal set:
`ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=`

**Comment by issa-tseng** [comment]
recall also that encodeURI_Component_ is not the same as encodeURI.

**Comment by matthew-white** [comment]
We discussed on the call today and decided to close out this issue.
