### ISSUE TITLE
Generate additional audit log entries?

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#274]
I'm noticing that when a user's password is set using /users/:id/password, a user.update audit log entry is created. However, /users/reset/initiate and /users/reset/verify do not similarly generate audit log entries. Should those endpoints also generate audit log entries?

**Comment by matthew-white** [comment]
One other thought, how about we have Central generate an audit log entry after backups are configured or terminated?

**Comment by florianm** [comment]
Another idea: audit changes to submitted data (once we can use Enketo to edit existing submissions)

**Comment by issa-tseng** [comment]
> Another idea: audit changes to submitted data (once we can use Enketo to edit existing submissions)

this is not in question.

**Comment by florianm** [comment]
The audit or updating existing submissions on ODK Central?

**Comment by issa-tseng** [comment]
whenever we do submission edit there's no way we don't audit the crap out of it

**Comment by florianm** [comment]
So you mean that submission edit is on the table? (Audit would be awesome but my project's holy grail is submission edit)

**Comment by matthew-white** [comment]
Submission edit is definitely on the table! It's listed under "Features we’ll likely add after June 2020" in a forum post [here](https://forum.getodk.org/t/whats-coming-in-central-over-the-next-few-years/19677).

**Comment by parthibd** [comment]
@matthew-white Hi! Is there any updates on the edit and delete submissions feature ?

**Comment by matthew-white** [comment]
Hi @parthibd! The upcoming release v1.2 will introduce related functionality. See getodk/central#198 for more information about that release.

**Comment by matthew-white** [comment]
About audit log entries, now that #331 is merged, I believe that more actions are being logged, which is great.

/v1/users/reset/verify now seems to generate two audit log entries: a `user.update` entry for the user and a `user.delete` entry for the single-use actor.

For the `user.update` entry, the actor is the single-use actor, which makes sense. The actor display name has the format "Reset token for [user id]". Frontend links that display name to a user page that 404s, so I think I should update Frontend to only render a link for the actor if the actor is a user.

For the `user.delete` entry, my instinct is that it'd be OK not to log an entry when a single-use actor is consumed.

Relatedly, a `user.delete` entry is now logged after an app user or public link is deleted (only possible right now over the API). Would it be possible to have the action that's logged depend on the actor type? For example, logging `field_key.delete` or `public_link.delete` rather than `user.delete`. Either way, I think I should update Frontend to display these new entries nicely.

An audit log entry is also now logged after backups are configured (though not after they are terminated). I'll plan to update Frontend to display those entries nicely.

I took a quick look at `lib/model/query/` to see if there are other new actions, but nothing stood out to me. @issa-tseng, let me know if there are any other changes you can think of that would be relevant to Frontend!

**Comment by issa-tseng** [comment]
i think i want to make single use actors not log at all bc they're internal details really

the rest makes total sense yes
