### ISSUE TITLE
Prevent user from deleting draft if form does not have published version

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#279]
I realized that there's an unusual edge case whereby a user can have a form without a published version and also without a draft. A user can't reach this state using Frontend, but they can do so using the API if they delete the draft of a form without a published version. I'm not doing much to account for this possibility in Frontend, so I think it'd be useful to prevent this case in Backend. How about if the user tries to delete the draft of a form without a published version, Backend returns a Problem?

This is definitely not a priority, but I think it'd make it slightly easier to reason about form versions. Maybe this would be a good issue for a contributor?

**Comment by issa-tseng** [comment]
ehhhhh i'm not sure i hate that this is possible. i'll think about it.

**Comment by matthew-white** [comment]
If a user has a form without a published version, then rather than delete its draft, I think the user should replace the draft, which we currently support. I think it would simplify things to be able to assume that every form without a published version has a draft. That'd mean that there'd be just two types of forms to reason about: draft forms and published forms. Right now there's a third type of form: unpublished yet also draft-less. If there's a use case for that third type, and we want to support it, that'd be good information too, because I'd keep that in mind while developing Frontend. I also think it'd be useful to highlight that case in the API docs, because I suspect that many downstream tools wouldn't consider that case otherwise. Again, not high priority though!

**Comment by issa-tseng** [comment]
i guess because it's not possible to _create_ a form without a schema it makes sense to always require one. i'll 409 in this case then.
