### ISSUE TITLE
Submissions with geoshape or geotrace result in error in Power BI 

### ISSUE THREAD

**Issue by yanokwa** [getodk/central-backend#294]
I made a basic form [geotrace.xlsx.zip](https://github.com/getodk/central-backend/files/5320504/geotrace.xlsx.zip), with a name field and a geotrace field. I used a public access link (Enketo) to submit it. I can see the data in the submissions view, but connecting it to Power BI gives me this error:

```
DataSource.Error: OData: An unexpected 'StartObject' node was found for property named 'geoshape' when reading from the JSON reader. A 'PrimitiveValue' node was expected.
Details:
    DataSourceKind=OData
    DataSourcePath=https://test.central.getodk.org/v1/projects/102/forms/geoshape.svc/Submissions
```

<img width="872" alt="Screen Shot 2020-10-02 at 2 58 31 PM" src="https://user-images.githubusercontent.com/32369/94973152-caa4e180-04bf-11eb-9530-1002c2979da4.png">

**Comment by lognaturel** [comment]
The error is now:

```
DataSource.Error: OData: Invalid GeoJSON. A primitive value was found in an array element where an array was expected.
Details:
    DataSourceKind=OData
    DataSourcePath=https://test.central.getodk.org/v1/projects/102/forms/geoshape.svc/Submissions
```

Note: PowerBI does not support GeoJSON according to https://community.powerbi.com/t5/Desktop/GeoJSON-through-OData/td-p/425604 https://github.com/getodk/central/issues/173

**Comment by issa-tseng** [comment]
probably between #321 and #322 this issue is covered by other tickets.

**Comment by lognaturel** [comment]
#321 did not address it.

**Comment by issa-tseng** [comment]
right but #322 will.
