### ISSUE TITLE
Docs for 409 on form creation are incorrect for v0.8+

### ISSUE THREAD

**Issue by lognaturel** [getodk/central-backend#296]
https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/forms states that "If the combination of (xmlFormId, version) conflict with any existing Form, current or deleted, the request will be rejected with error code 409. We consider even deleted forms when enforcing this restriction to prevent confusion in case a survey client already has the other version of that Form downloaded."

I believe that there will be a 409 if there is a currently-published form with the provided `xmlFormId`. However, if a form with the provided `xmlFormId` was previously deleted, a new draft will successfully be created even if there's a `(xmlFormId, version)` conflict. The uniqueness check will be done on publish.

**Comment by issa-tseng** [comment]
i'll just delete the line then.
