### ISSUE TITLE
Form definitions pushed from Briefcase to encrypted project do not get encryption key

### ISSUE THREAD

**Issue by lognaturel** [getodk/central-backend#298]
1. Turn on project-level encryption
1. Post and publish a form definition from Briefcase and see that no encryption key is added to the form definition
1. Submit unencrypted submissions and see that they succeed

https://test.central.getodk.org/#/projects/140/forms/all-widgets as an example

Briefcase posts the form definition to create the form, then posts and publishes drafts for any form versions it knows about.

**Comment by issa-tseng** [comment]
but i see this?

`<submission base64RsaPublicKey="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA428vV9L/Czo7Vd6C+HkT9sOVFTVXY2isxj2jQfFbkFktxeuOb7WUV52OzVIYRCmOsrg81Ymx0q4zWF0cbCSglfvb3UopLYSKFdeeJ+hin/zGR5srJmihnpQLzh4LS78MYQwMLiJizWEyj20WyRd5cfxgsD4e2w2WY/cuHENnTrM/uDs7SjkCauLJGNGdRzFYAYvP8W85wmUuV3MIVxJjy5u+2AQ7LxbImQNDr1G6i/61doG6IG0EbP2Zn3cBZW8N90B9Y8eGo+aZe/ZpmygQi7DBYrAPnWL2kvxHHag/ux2+X/bRMJY0olYVwwn6qMFBqUNRyAmIm9eEsnE7GRomhQIDAQAB"/>`

**Comment by issa-tseng** [comment]
did this get resolved?

**Comment by lognaturel** [comment]
I don’t believe so but will need to check again.

**Comment by mmarciniak90** [comment]
I think I got the same result but I did it in a bit different way, using Collect.

1. Create a new project, add and publish form
2. On Collect, scan QR code to download the form
3. Fill and submit submission(s)
4. Turn on project-level encryption
5. New form version is downloaded on Collect
6. Disable hiding old form versions - both versions are visible. This allows you to select which version you want to complete and submit.
7. Sending both versions is possible and cause a mess on Central's submission list

|Collect |<img height="20%" src="https://user-images.githubusercontent.com/3907554/116064454-52358600-a686-11eb-8d19-761495c90a95.png">|
|---|---|
|Central|<img width="1011" alt="Zrzut ekranu 2021-04-26 o 11 54 48" src="https://user-images.githubusercontent.com/3907554/116064409-46e25a80-a686-11eb-866e-b12cba37c922.png">|

**Comment by kkrawczyk123** [comment]
@lognaturel @issa-tseng I am still able to reproduce this issue. I will write the exact steps I followed:
1. I created a new encrypted project on Central
2. Uploaded All wigdgets.xml to Central - it became encrypted (I was able to download encrypted form to Collect and fill submission and send it - submission is encrypted on Central)
3. I pushed using Briefcase All widgets form the same number of version but not encrypted form with submissions.
4. Not encrypted submissions are visible in Central - and new non-encrypted form version is visible in Versions on Central, see:
https://test.central.getodk.org/#/projects/285/forms/all-widgets/versions so the currently published version is non-encrypted. When I downloaded the form on Collect I was able to fill and send a non-encrypted form.
Essentially, it should not be allowed to add a new unencrypted version of form (and it's submission) when the project is encrypted. It is not allowed manually so it shouldn't be possible via Briefcase push. 

The behavior that @mmarciniak90 described is actually an expected one as both versions of form are already on Central. I have also verified sending submission of a not encrypted version of form when the encrypted version is on Central - I have obtained sending error: Could not find the resource you were looking for. It is not possible to reproduce that issue using Collect.

**Comment by mmarciniak90** [comment]
You are right! 👍 
The result on the submission list is the same but the difference is in the version list.

| <img width="517" alt="Zrzut ekranu 2021-04-26 o 14 53 13" src="https://user-images.githubusercontent.com/3907554/116085775-72257380-a69f-11eb-8020-dd7571f01c2c.png">|<img width="547" alt="Zrzut ekranu 2021-04-26 o 14 53 28" src="https://user-images.githubusercontent.com/3907554/116085778-73ef3700-a69f-11eb-9b30-e3d9535fcbf3.png">|
|---|---|

**Comment by lognaturel** [comment]
Thanks so much for helping us get clarity on what's going on, @kkrawczyk123, @mmarciniak90.

I think the root issue is that if a **project** is encrypted, it's possible to publish a form version without encryption and that this is unexpected. The expectation would be that this new version automatically gets an encryption key on publish but that is not currently the case when forms are uploaded and published through the API without the frontend being involved. Does that sound right?

I agree that what @mmarciniak90 experienced is currently expected. I think that as a separate issue, we should consider also revising that behavior. That is, if a form was deployed without encryption and then project-level encryption is turned on, perhaps the older versions of the form should be modified to require encryption or should be archived to ensure that all subsequent data comes in encrypted.

I don't think either issue is urgent. I don't think they should be considered for v1.2 unless they turn out to be trivial to fix.

Side note -- the links here were from `test.central.getodk.org` because the issue predates `http://test.getodk.cloud/`. Please make sure you use `test.central.getodk.org` only for backup testing. For everything else, `http://test.getodk.cloud/` is the server to focus on.

**Comment by issa-tseng** [comment]
when a project gets encrypted, all forms within it are supposed to get encrypted at that point, including outstanding drafts. all incoming forms to an encrypted project are supposed to get encrypted if they are not already. if central is doing anything other than that it's a regression.

but i can't tell from this discussion what the actual problem trigger is or what of the above is true.

i disagree that older versions of the form should be modified to require encryption—this makes them essentially useless. their sha will change, their version string will change, etc etc. i'd sooner delete or deactivate old versions than modify them like that.

**Comment by issa-tseng** [comment]
the frontend does not do any encryption things, nor does it access anything briefcase does not. the issue is probably with something briefcase is doing to the definition?

**Comment by lognaturel** [comment]
Could it be that backend allows publishing a draft version that was replaced by another draft version? That is, in a draft session, I might upload versions 1 and 2. Frontend only lets me issue a publish for version 2 but might the API allow a publish on version 1?

**Comment by issa-tseng** [comment]
that's not a concept. if you replace a draft you replace the draft. version 1 does not exist.

in general, the frontend does roughly _zero_ safety checks. the backend enforces everything. anything the frontend checks is for convenience, in duplicate w the backend's enforcement.

i'll point out again the curiosity at the start of this thread and some facts:
1.  when encryption is enabled, all [existing forms](https://github.com/getodk/central-backend/blob/master/test/integration/api/projects.js#L442) and all [draft forms](https://github.com/getodk/central-backend/blob/master/test/integration/api/projects.js#L478) are encrypted.
2. all [subsequently uploaded](https://github.com/getodk/central-backend/blob/master/test/integration/api/projects.js#L516) forms are encrypted.
3. but central leaves forms alone [that it thinks are already encrypted](https://github.com/getodk/central-backend/blob/master/test/integration/api/projects.js#L462).
4. at the top of this thread, you complain that a form does not have encryption on it.
5. but that form _does_ have `<submission base64RsaPublicKey="` etc on it.
6. central will interpret fact #5 as the form being encrypted. but is something _wrong_ w the declaration?
7. and why is it there? you told me the form is not encrypted.

**Comment by lognaturel** [comment]
> but that form does have <submission base64RsaPublicKey=" etc on it.

Got it, I didn't realize that you were referring to the subsequent versions and didn't previously go back to check myself. I believed the subsequent versions did not have the encryption key.

So @kkrawczyk123 ended up with a form definition that has the project-level encryption key and modified it to change the version identifier. She also ended up with non-encrypted submissions with the same form version identifier that were presumably generated with another form definition with the same version identifier. This is possible because two different form definition versions can indeed have the same version identifier. But it's not something that would happen in normal usage. 

I think we're left with:
- It feel unexpected that Central accepts non-encrypted submissions for a form definition with an encryption key
- After project-level encryption is turned on, it feels unexpected that submissions for versions without encryption are accepted 

Are these worth filing issues for?

**Comment by issa-tseng** [comment]
your call on the first point. i never really thought about it, i just take whatever the client gives. i guess if the client has already decided to transmit data in cleartext is it really a better result to reject it, where probably the user will just try to submit it again in cleartext? or is it better to reject and force the issue for future submissions, even though cleartext will still get sent in the meantime?

the second point: i think we wrap back around to the discussion of (optionally?) disabling submissions for old versions if encryption is on the new version.
