### ISSUE TITLE
500 error if backup code is incorrect

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#303]
While setting up backups using Frontend, if the confirmation text you enter is incorrect, Backend returns a 500 with the message "Completely unhandled exception: Cannot read property 'data' of undefined".

From a first look, it seems that Google returns an object with a property named `response`, but Backend expects a property named `res`:

https://github.com/getodk/central-backend/blob/e9ffd2c0c3aa1a9475852e1397b8259e2b03165a/lib/resources/config.js#L71-L73

I think this explains this Sentry issue: https://sentry.io/organizations/getodk/issues/1875192039/?project=1298632

**Comment by issa-tseng** [comment]
sigh. they change this all the time and they don't document it.
