### ISSUE TITLE
Clarify what types are returned by the fields and Odata schema endpoints

### ISSUE THREAD

**Issue by mtyszler** [getodk/central-backend#306]
When using the API call to get the form schema (https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/'-individual-form/getting-form-schema-fields) or using ruODK form_schema(), the type returned is not correct. For example, select1 fields are marked as "string".

See below, for example:

![image](https://user-images.githubusercontent.com/23292639/98244371-a1b8b600-1f6f-11eb-9104-fe164b823f4f.png)

See:  https://forum.getodk.org/t/incorrect-type-returned-by-api-form-schema-fields/31044
See: https://github.com/ropensci/ruODK/issues/101

**Comment by lognaturel** [comment]
In XForms, selects are considered a view-only concern. The underlying type is indeed string. To get that a field is a select, you would need to look at the form definition body.

**Comment by lognaturel** [comment]
Thanks for going to the forum, that’s generally a better place to start conversations. I added more details af https://forum.getodk.org/t/incorrect-type-returned-by-api-form-schema-fields/31044/2

**Comment by mtyszler** [comment]
> In XForms, selects are considered a view-only concern. The underlying type is indeed string. To get that a field is a select, you would need to look at the form definition body.

Tks for the clarification.
