### ISSUE TITLE
Date type properties rendered as String and not Date in OData API

### ISSUE THREAD

**Issue by larshelge** [getodk/central-backend#325]
In the Odata API, it appears as date type fields are represented as strings / `Edm.String`. It would be more appropriate to render date fields as `Edm.Date`.

More specifically, there are several date related field types such as "Date", "Date without calendar", "Month and year", "Year" which are captured using date pickers and rendered in the ISO `yyyy-MM-dd` format in the API output. However, in the OData metadata response, these properties are rendered with type `Edm.String`. The OData standard supports `Edm.Date` which would be more appropriate here.

My use-case is loading ODK OData submissions into a data warehouse, in which case it will be useful to map to a `date` field rather than `varchar` or `text`.

This can be tested with the "all widgets" sample form by observing e.g. the "date_widget" property.

![date-type](https://user-images.githubusercontent.com/908206/103482715-b33d0380-4de2-11eb-90c9-4a0a4b1a464d.png)

**Comment by issa-tseng** [comment]
i'm trying to remember why i decided against doing this originally.
maybe i just didn't see that there is a Date type. maybe there wasn't one at the time.
i'm confused why i didn't do this.

**Comment by larshelge** [comment]
Okay, thanks @issa-tseng for the reply. I am thinking it would be great to define dates as `Edm.Date`, as clients could still chose to handle dates as strings if they would like; in the current situation clients are not able to know which fields are dates and handle them as dates.
