### ISSUE TITLE
Misleading response error message in API from authenticating

### ISSUE THREAD

**Issue by jkpr** [getodk/central-backend#329]
I was trying out the API, I got a session token, and then I was sending the token in Python as 

```python
session_token = "MY_TOKEN_HERE"
auth_header = {"Authorization": f"Bearer: {session_token}"}
```

with an extra colon `:` after `Bearer`. When I requested project forms at URL `/v1/projects/<project_number>/forms` the response was a 403

```
{"message":"The authenticated actor does not have rights to perform that action.","code":403.1}
```

This web user with the session was confirmed to have access to that project. The error message is misleading because I thought the server understood who I was based on the message. In fact, it did not understand who I was, and when I removed that extra colon to be

```python
session_token = "MY_TOKEN_HERE"
auth_header = {"Authorization": f"Bearer {session_token}"}
```

I got the data that I was expecting. I would have liked the error message to be something like "Authorization header sent, but it does not match any current user or session".

**Comment by matthew-white** [comment]
Hi @jkpr! We generally don't distinguish between "the actor doesn't exist" and "the actor doesn't have rights": both cases result in a 403, specifically with a `code` property of 403.1. I can see the potential confusion though given the message. @issa-tseng, what do you think about changing the message to something that explicitly mentions both cases? Maybe something like "The actor does not exist or does not have rights to perform that action."?

**Comment by jkpr** [comment]
Actually, looking into this a little bit more, a 401 seems more appropriate. From https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

> The HTTP 401 Unauthorized client error status response code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.

If I incorrectly format the Authorization header, then the server could naturally and appropriately respond "401 the request lacks valid authentication credentials". A 403 tells me that the server knows who I am but I am forbidden from accessing the resource, and that isn't the case here.

**Comment by issa-tseng** [comment]
so, everyone's got some truth here

on one hand, i don't want to information-leak the existence of tokens via the difference between 401/403. this is yes counter to the exact http semantics but it is not an uncommon practice i think. so we tend to log things on the side of  a 403 rather than a 401.

on the other hand, the issue you mention above is a _formatting_ error, not an existence error. i have revised the code to return a 401 in this instance. i hope that sounds alright.

**Comment by issa-tseng** [comment]
(i also revised the message)
