### ISSUE TITLE
Include "instance ID" first column to the combined client audit CSV export

### ISSUE THREAD

**Issue by lognaturel** [getodk/central-backend#333]
Collect can record an audit log of data collectors’ actions if it is requested by a form ([documentation](https://docs.getodk.org/form-audit-log/)). For forms that request audits, a Central ZIP export includes a summary CSV that combines logs from all submissions. That export does not connect audit events to the submissions they belong to [as reported on the forum](https://forum.getodk.org/t/31887).

The implementation will require careful changes to the database schema so that the export remains performant.

**Comment by matthew-white** [comment]
Closed by #335. 🎉
