### ISSUE TITLE
lib/bin/cli.js prints "undefined"

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#334]
When I use `lib/bin/cli.js`, I see the text "undefined" when I run the tasks `user-create` and `user-promote`. I think previously `user-create` displayed JSON about the new user, and `user-promote` indicated success.

I took a quick look at things, and I think the relevant logic is here:

https://github.com/getodk/central-backend/blob/dab8530c8c07f8b3b6bc56aae5c46c4c0e351358/lib/task/task.js#L54-L62

I think the function that `cleanup()` returns isn't returning a promise.

Just an idea, would `finally()` work here?

**Comment by matthew-white** [comment]
Also, I think relatedly, if a task fails, then I see an `UnhandledPromiseRejectionWarning`. (For example, after trying to create a user with an email already in use.)

**Comment by matthew-white** [comment]
This seems to be affecting Google backups as well. When `lib/bin/backup.js` is run on a server for which backups are configured, an error is thrown:

<details>
<summary>stack trace</summary>
<pre><code>service               | UnexpectedStateError: Connection pool shutdown has been already initiated. Cannot create a new connection.
service               |     at Object.createConnection (/usr/odk/node_modules/slonik/dist/factories/createConnection.js:22:15)
service               |     at Object.query (/usr/odk/node_modules/slonik/dist/binders/bindPool.js:14:32)
service               |     at obj.run (/usr/odk/lib/util/db.js:176:23)
service               |     at /usr/odk/lib/model/query/audits.js:24:10
service               |     at Object.module.<computed> [as log] (/usr/odk/lib/model/container.js:30:33)
service               |     at /usr/odk/lib/task/task.js:98:10
service               |     at /usr/odk/lib/task/task.js:51:44
service               |     at /usr/odk/lib/task/task.js:111:17
service               |     at processTicksAndRejections (internal/process/task_queues.js:85:5)Failed to audit-log task failure message!
service               | UnexpectedStateError: Connection pool shutdown has been already initiated. Cannot create a new connection.
service               |     at Object.createConnection (/usr/odk/node_modules/slonik/dist/factories/createConnection.js:22:15)
service               |     at Object.query (/usr/odk/node_modules/slonik/dist/binders/bindPool.js:14:32)
service               |     at obj.run (/usr/odk/lib/util/db.js:176:23)
service               |     at /usr/odk/lib/model/query/audits.js:24:10
service               |     at Object.module.<computed> [as log] (/usr/odk/lib/model/container.js:30:33)
service               |     at /usr/odk/lib/task/task.js:98:10
service               |     at /usr/odk/lib/task/task.js:51:44
service               |     at /usr/odk/lib/task/task.js:111:17
service               |     at processTicksAndRejections (internal/process/task_queues.js:85:5)
<strong>service               | TypeError: Cannot read property 'value' of undefined
service               |     at /usr/odk/lib/bin/backup.js:28:41</strong>
service               |     at processTicksAndRejections (internal/process/task_queues.js:85:5)
</code></pre>
</details>

`getConfiguration()` seems to return a promise that resolves to `undefined` rather than resolving to a `Config`. I think that's because `getConfiguration()` runs `task.withContainer()`, which runs the block mentioned above.

**Comment by matthew-white** [comment]
I'm also thinking that the two "Connection pool shutdown has been already initiated." errors in the stack trace above are coming from `auditing()` and `emailing()`. I think `task.withContainer()` is being called three times (by `auditing()`, `emailing()`, and the async function in `backup.js`), and each call is running `slonikPool()`. Is that expected? In terms of the timing by which those three connections are created, I think a new connection is attempted before the previous pool shutdown is complete because `cleanup()` isn't returning a promise.

**Comment by issa-tseng** [comment]
oh neat finally is new.
