### ISSUE TITLE
OData subtable: $top=0 returns all records

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#337]
When I specify `$top=0` for the `Submissions` table, it returns an empty array. However, when I specify `$top=0` for a subtable, it seems to return all records.

As background, I was specifying `$top=0` together with `$count=true` in order to determine the number of records in a repeat group, related to [this](https://forum.getodk.org/t/the-endpoint-to-return-the-number-of-rows-within-the-repeat-table/32699) forum post. I ended up specifying `$top=1` in order not to pull all records. (By the way, I would also be interested if there is a better way to determine that count!)

I think this logic can be found in the `extractPaging()` function below, where if `limit` is 0, it defaults to `Infinity`:

https://github.com/getodk/central-backend/blob/dab8530c8c07f8b3b6bc56aae5c46c4c0e351358/lib/formats/odata.js#L53-L62

**Comment by issa-tseng** [comment]
looks like odata doesn't have any independent count-only endpoint so we'd have to make one if we wanted one

**Comment by matthew-white** [comment]
That's interesting that OData doesn't have an independent count-only endpoint. What do you think about using the combination of `$count=true` + `$top=0` to fetch just the count?

**Comment by issa-tseng** [comment]
yeah i'll fix this top thing  rn
