### ISSUE TITLE
$filter: add links and example to API docs

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#338]
@aurdipas [suggests](https://forum.getodk.org/t/central-api-examples/32335) on the forum:

> I had to give some support to folk that wanted to use the ODK Central API to extract data.
>
> I think it would be useful to have some examples for user not so experienced.
>
> &hellip;
>
> Maybe some links to OData [Built-in Filter Operations](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_BuiltinFilterOperations) or [Built-in Query Functions ](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_BuiltinQueryFunctions) directly on the page of [export submissions ](https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/submissions/exporting-form-submissions-to-csv) and some practical examples on filters:
>
> e.g. I want to filter submission between 2 dates "filter=__system%2FsubmissionDate%20gt%202021-01-01%20and%20__system%2FsubmissionDate%20lt%202021-01-31"

I think a short example of `$filter` would be quite helpful, especially since the OData syntax is also used for the .csv.zip endpoint.

**Comment by issa-tseng** [comment]
addressed in #360, though i am certain there is more could be done and we will.
