### ISSUE TITLE
Don't log error when Google Drive backups are not configured

### ISSUE THREAD

**Issue by lognaturel** [getodk/central-backend#346]
When backups are not configured, they still make an attempt to run every 24 hours. This results in the error message `{"0":"n","1":"o","2":" ","3":"b","4":"a","5":"c","6":"k","7":"u","8":"p","9":" ","10":"c","11":"o","12":"n","13":"f","14":"i","15":"g","16":"u","17":"r","18":"e","19":"d","success":true}` every day in the backup log. e.g. https://sandbox.getodk.cloud/#/system/backups

If backups are not configured, there's already a big notice at the top of the backups page. There should not be a daily log message.

**Comment by issa-tseng** [comment]
i guess the reason i log at all is bc i don't fully trust how i'm running cron and i'd like to know that the script is running at all. is it a big deal it logs?

**Comment by lognaturel** [comment]
It's scary and confusing to users, especially in its current incarnation. Maybe frontend could only display the log section if backups are configured?

**Comment by issa-tseng** [comment]
obv i'll fix the message (did already actually)

**Comment by issa-tseng** [comment]
oh okay i'm good w that. also if the message  is fixed it's probably not so bad

**Comment by lognaturel** [comment]
Great! So I think this can be closed, then, and we can evaluate what the new message looks like and see whether we want to do the frontend issue. It's true it might feel less like something terrible has happened with a message that looks more intentional.

**Comment by issa-tseng** [comment]
it says (lol)

`{ "did": "nothing", "because": "no backup configured"}`

**Comment by lognaturel** [comment]
😅
