### ISSUE TITLE
Basic Auth results in 500

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#350]
@lognaturel received a 500 while using Power BI, corresponding to this Sentry issue:

https://sentry.io/organizations/getodk/issues/2308979614/?project=1298632

From a first look, the issue seems to be that the `sessionHandler()` preprocessor is using `User.getByEmail()` rather than `Users.getByEmail()`. I think that object changed as part of #331. I believe that tests are passing because they mock the `User` object.

**Comment by issa-tseng** [comment]
:(
