### ISSUE TITLE
Catch error for manual backup?

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#352]
I just tried completing a manual backup of a server that uses Postgres v12. I believe the backup attempt failed immediately due to a Postgres version mismatch. However, the request itself didn't fail for 23 minutes:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 32065    0 32065    0     0     22      0 --:--:--  0:23:16 --:--:--     0
curl: (18) transfer closed with outstanding read data remaining
```

I believe the 23 minutes corresponds to how long it took to trickle the 32 KB of random data (+ maybe a minute or two before timeout?).

Would it be possible to return an error response or at least to immediately stop trickling if there's a `pgdump()` error? I believe that the backup task will catch a `pgdump()` error, but I think /v1/backup won't. Seems like it might be good to at least avoid a potential uncaught promise error? Unless we only expect `pgdump()` to throw in unusual cases like a version mismatch?

**Comment by issa-tseng** [comment]
we can halt the request right away probably. but there’s no possibility to handle it gracefully.
