### ISSUE TITLE
Add ability to restore backup >10 GB?

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#353]
On the forum ([here](https://forum.getodk.org/t/central-backup-restore/33047)), a user reports that their backup .zip file is greater than 10 GB (almost 12 GB). However, `lib/bin/restore.js` will not restore a backup whose uncompressed size is greater than 10 GB. For comparison purposes, a backup .zip file from the QA server is a little over 6 GB.

Is it possible/wise to increase this limit? Alternatively, could we add a CLI flag that when specified would allow a backup >10 GB to be restored?

**Comment by issa-tseng** [comment]
ah. this is a technological misunderstanding. the zipfile library refuses by default to unzip anything >10GB presuming it to be a DoS attack. i can see if we can turn it off just for that case.
