### ISSUE TITLE
OData: Missing fields in repetitions

### ISSUE THREAD

**Issue by vituslehner** [getodk/central-backend#356]
Hi all!

There appears to be a bug with OData submission responses where fields in repeat groups are missing under certain circumstances.

If a repeat group was not populated with data but the repeat contains non-null calculate fields, the normal fields do not occur in the OData response, even though the repeat has a repetition. More interestingly, fields that are in a group within the repeat do not seem to be missing, even if unpopulated. See example XLSForm attached. If submitted empty, the fields "repeated_text" and "repeated_number" will not arrive via API. Inner-group fields will.

This was tested on version:
```
versions:
647569c54f6bbf26ea356eca0d14f7e5d1a89c6b
 cddb691e40e84aabff87b9d427e22a50282d6f99 client (v1.1.2)
 a33bc6fb3c34fe38894b0e9d0bb404f81da325e6 server (v1.1.1)
```

Example response of a populated repeat (which for me is **expected behaviour** with all fields included):
`/v1/projects/4/forms/missing_fields_dv6.svc/Submissions('uuid:065ef741-e991-408c-a4db-7dd3c12ba57c')/g1/repetition?$top=250&$skip=0&$count=true`
```json
{
   "value":[
      {
         "__id":"2883991111cd54f2af5f9844b94af7c6eac2514e",
         "__Submissions-id":"uuid065ef741-e991-408c-a4db-7dd3c12ba57c",
         "repeated_group":{
            "inner_repeated_number":7,
            "inner_repeated_calc":"7inner"
         },
         "repeated_number":8,
         "repeated_text":"eight",
         "repeated_calc":"8eightrepeated"
      }
   ],
   "@odata.context":"https://example.com/v1/projects/4/forms/missing_fields_dv6.svc/$metadata#Submissions.g1.repetition",
   "@odata.count":1
}
```

Example response of an unpopulated repeat (which for me is **unexpected behaviour**, aka fields missing):
`/v1/projects/4/forms/missing_fields_dv6.svc/Submissions('uuid:dae7f9f0-1f74-47f8-851c-d7498ececa6c')/g1/repetition?$top=250&$skip=0&$count=true`
```json
{
   "value":[
      {
         "__id":"a2b3679d1a4acb0c0f243856cfcbb3a253a29bd7",
         "__Submissions-id":"uuid:dae7f9f0-1f74-47f8-851c-d7498ececa6c",
         "repeated_group":{
            "inner_repeated_number":null,
            "inner_repeated_calc":"inner"
         },
         "repeated_calc":"repeated"
      }
   ],
   "@odata.context":"https://example.com/v1/projects/4/forms/missing_fields_dv6.svc/$metadata#Submissions.g1.repetition",
   "@odata.count":1
}
```
[central_missing_fields.xlsx](https://github.com/getodk/central-backend/files/6294549/central_missing_fields.xlsx)

As was noted by @issa-tseng in Slack, could the following commit be a fix for this issue? https://github.com/getodk/central-backend/commit/5a8ec9508e8974205edae5117bbf8210110006c7

**Comment by mattelacchiato** [comment]
In my case the commit of 5a8ec9508e8974205edae5117bbf8210110006c7 did not work...

**Comment by vituslehner** [comment]
Yes, same for me. The commit did not solve it for the example file above.

**Comment by issa-tseng** [comment]
hey @vituslehner, thanks again for the thoughtful report. is it possible to get the submission xml for these examples as well? i'll take a look to get this patched for our next release.

**Comment by vituslehner** [comment]
Hi @issa-tseng thanks for your response for getting into it! These are the submission XMLs:

Populated fields:
```xml
<data
	xmlns:jr="http://openrosa.org/javarosa"
	xmlns:orx="http://openrosa.org/xforms" id="missing_fields_dv6" version="1">
	<g1>
		<repetition>
			<repeated_group>
				<inner.repeated_number>7</inner.repeated_number>
				<inner.repeated_calc>7inner</inner.repeated_calc>
			</repeated_group>
			<repeated_number>8</repeated_number>
			<repeated_text>eight</repeated_text>
			<repeated_calc>8eightrepeated</repeated_calc>
		</repetition>
		<number>3</number>
		<text>three</text>
		<calc>3three</calc>
	</g1>
	<meta>
		<instanceID>uuid:fa0d6b99-f0d6-4998-a81b-4c532dd79a68</instanceID>
	</meta>
</data>
```

Unpopulated fields:
```xml
<data
	xmlns:jr="http://openrosa.org/javarosa"
	xmlns:orx="http://openrosa.org/xforms" id="missing_fields_dv6" version="1">
	<g1>
		<repetition>
			<repeated_group>
				<inner.repeated_number/>
				<inner.repeated_calc>inner</inner.repeated_calc>
			</repeated_group>
			<repeated_number/>
			<repeated_text/>
			<repeated_calc>repeated</repeated_calc>
		</repetition>
		<number/>
		<text/>
		<calc/>
	</g1>
	<meta>
		<instanceID>uuid:7ce406ba-c281-4d64-bd32-b79b394f1047</instanceID>
	</meta>
</data>
```

Looks like `repeated_number` and `repeated_text` arrive here, though empty of course.

**Comment by issa-tseng** [comment]
hey @vituslehner, let me make sure i'm understanding the problem correctly. the issue is not that _values_ are being forgotten, but rather than empty field headers are not being produced?

what is the result you _expect_ to see in the second case? i'm sort of comparing across odata and xml and it looks to me like all the _values_ are there, so i'm guessing what you're looking for is eg `repeated_text: null` and `repeated_number: null` ?

**Comment by vituslehner** [comment]
Yes exactly, I would expect those empty fields to show up, even though they'd be set to `null`. Outside of the repeat, empty fields are shown that way, too. And interestingly, empty fields **in a sub-group within the repeat** seem to show up as well (`inner.repeated_number`/`inner_repeated_number`).

**Comment by issa-tseng** [comment]
okay y'all i think eca2e4412a8a9a379c0187062a753ab53631d175 should do it.

**Comment by vituslehner** [comment]
@issa-tseng Sorry for the late reply. Works for me as well, thanks a lot!
