### ISSUE TITLE
$filter operators : gt works as gte and lt as lte, lte and gte don't  work

### ISSUE THREAD

**Issue by mathieubossaert** [getodk/central-backend#358]
Using $filter to get a subset of submissions filtered on "__system/submissionDate" I realize that, as if the documentation mention that gt, gte, lt and lte are supported, I face a problem.
Filtering with lte or gte returns no submission, filtering with gt or lt returns submissions having respectively submission date greater or equal and lower or equal to $filter value

```bash
curl --user "user:password" https://central.myserver.org/v1/projects/5/forms/Sicen.svc/Submissions?%24filter=__system%2FsubmissionDate%20gt%202021-04-14
```
returns submissions starting on 2021-04-14

**Comment by issa-tseng** [comment]
hey mathieu:

i'm not sure what you're seeing with gte and lte, but the issue with gt and lt, i'm pretty sure, is that submissionDate is actually a dateTime column, and so it's not incorrect, it's just judging things down to the millisecond.

if you use the `year()`/`month()`/`day()` extraction functions you can get back integers to compare against instead.

**Comment by mathieubossaert** [comment]
Hi @issa-tseng, 

Thanks a lot for your answer.
gte and lte operators returns no result.

If I use '2021-03-01' the server returns those submission dates (could be ok with the fact it considers : '2021-03-01T00:00.000Z') : 
"2021-03-01T07:44:25.704Z"
"2021-03-01T07:44:26.622Z"
"2021-03-02T18:19:38.767Z"
"2021-03-02T18:19:39.140Z"

But If I use '2021-03-01T07:44:26.622Z' I would have expect the same result as above without the first to lines.. But it only skip the first one,
"2021-03-01T07:44:26.622Z"
"2021-03-02T18:19:38.767Z"
"2021-03-02T18:19:39.140Z"

I need to use '2021-03-01T07:44:26.623Z' to fetch the result I want.

I would like to use this filter to get only lines from central with a submission date strictly greater than the highest one already in my database.
But that rises another question, maybe off topic... Does submission_date depends on phone time settings or is it given by Central whan the data is send to it.
I I found a workaround in may database as, if my last API call overlaps some submissions I already pulled, I ignore it.

**Comment by matthew-white** [comment]
Hi @mathieubossaert!

> gte and lte operators returns no result.

I think the OData operators are ge/le, not gte/lte. If you're using gte/lte, you should see an error message.

> If I use '2021-03-01' the server returns those submission dates (could be ok with the fact it considers : '2021-03-01T00:00.000Z') :
> "2021-03-01T07:44:25.704Z"
> "2021-03-01T07:44:26.622Z"
> "2021-03-02T18:19:38.767Z"
> "2021-03-02T18:19:39.140Z"
> 
> But If I use '2021-03-01T07:44:26.622Z' I would have expect the same result as above without the first to lines.. But it only skip the first one,
> "2021-03-01T07:44:26.622Z"
> "2021-03-02T18:19:38.767Z"
> "2021-03-02T18:19:39.140Z"
> 
> I need to use '2021-03-01T07:44:26.623Z' to fetch the result I want.

I think that by default, Postgres `timestamp` values are more precise than millisecond. The value in the database might be less than a millisecond after 2021-03-01T07:44:26.622Z.

> I would like to use this filter to get only lines from central with a submission date strictly greater than the highest one already in my database.

That makes a lot of sense to me, and I think that will be a common use case. I wonder if it's possible to discard the sub-millisecond part of `submissions.createdAt`, either when storing it or when filtering based on it (@issa-tseng would know for sure). Otherwise, I think what you're doing to ignore duplicates would be the right approach.

> But that rises another question, maybe off topic... Does submission_date depends on phone time settings or is it given by Central whan the data is send to it.

The submission date is the time that the server receives the submission.

**Comment by mathieubossaert** [comment]
Hi @matthew-white 

> I think the OData operators are ge/le, not gte/lte. If you're using gte/lte, you should see an error message.
You're right. AS my curl call is within a SQL function I do not catch the message... #{"message":"The OData filter expression you provided could not be parsed: "
But the documentation is confusing AS it mentions both lte and gte operators : 
https://odkcentral.docs.apiary.io/#reference/odata-endpoints/odata-form-service/data-document

> either when storing it or when filtering based on it (@issa-tseng would know for sure). Otherwise, I think what you're doing to ignore duplicates would be the right approach.
No emergency for it as if some submissions wher already pulled they will be ignored in my database

> The submission date is the time that the server receives the submission.
Great !

Thanks a lot to you both, I am on my way to document a clean method to retrieve data within ouo PostGIS database without any external tool except curl.

**Comment by issa-tseng** [comment]
oops. i'll fix the doc. i'll also try to clarify what you just saw. thanks!
