### ISSUE TITLE
Update Sentry SDK from version 5.7.1 to version 6.3.5

### ISSUE THREAD

**Issue by yanokwa** [getodk/central-backend#371]
Sentry says "We recommend you update your SDK from version 5.7.1 to version 6.3.5". They link to https://docs.sentry.io/platforms/javascript/.

5.7.1 was released in 2019, so it's pretty old.

**Comment by issa-tseng** [comment]
do you think this for 1.2 or following? we're in qa already..

**Comment by yanokwa** [comment]
After v1.2 for sure.

**Comment by issa-tseng** [comment]
lol now it's 6.11
