### ISSUE TITLE
Postgres connection string

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#377]
Filing an issue in connection with this forum post: https://forum.getodk.org/t/connection-timeout-after-upgrading-to-central-v1-2/33690

In v1.1, we passed the `default.database` config to Knex. In v1.2, we construct a connection string using the config, then pass it to Slonik:

https://github.com/getodk/central-backend/blob/24d20de20fdf2e03b55e687542fbc0cae889a9ff/lib/external/slonik.js#L15-L18

However, I think there are differences in some cases:

- I think we need to percent-encode special characters in the password.
- It used to be possible to specify a `port` property, though I don't think we documented that. I think the user can just specify the port as part of the `host` property, right?
- It used to be possible to specify the named parameter `?ssl=true` (by specifying `"ssl": true` in the config), though again I don't think we documented that. It seems like that might something that'd be useful to officially support?

One idea is that we could allow `default.database` to be either an object or a string. That way, if you're using the typical properties, you can use the object, but if you want to do something else, you can specify a string.

**Comment by lognaturel** [comment]
Possibly tangentially related: https://github.com/getodk/docs/issues/1250

**Comment by matthew-white** [comment]
Another idea: I noticed in the [docs](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING) that

> Values that would normally appear in the hierarchical part of the URI can alternatively be given as named parameters. For example:
>
> ```
> postgresql:///mydb?host=localhost&port=5433
> ```

So maybe we could just convert everything in the config object (except `database`) to a query string?

**Comment by florianm** [comment]
I have indeed run into this issue with SSL and will post more details about my attempts here. Thanks for keeping my use case in mind!

**Comment by matthew-white** [comment]
One possibility that @issa-tseng suggested is to add an optional property through which a connection string could be specified. This would be the way to specify things like SSL options. It'd be something like:

- If `host` and `database` are specified, then use the basic config properties (host, database, user, password) to construct the connection string
- If `dbstring` is specified, then use that as the connection string
- Throw an error if both sets of options are specified

I also think it'd be useful to throw an error if the user specifies an option that we don't know how to use. That would help catch cases where the user tries to use Knex options that are no longer supported.

<hr>

One other thing I realized as part of the most recent [forum discussion](https://forum.getodk.org/t/odk-central-with-custom-database-with-ssl/34435) is that we use the config in two different ways:

1. We use a subset of config properties to construct a connection string to pass to Slonik
2. We pass the config as-is to Knex, which we use for migrations

I think it'd be useful to connect to Slonik and Knex in the same way (using the same options). Perhaps we should always connect to Knex using a connection string, like we do with Slonik? Or we could continue passing the config to Knex, but throw an error if the user specifies an unknown option?

One place where things get a little complicated is `rejectUnauthorized`, an SSL option. By default, `rejectUnauthorized` is `true` (I think). That means that before, when we used Knex, I think you had to specify `false` for `rejectUnauthorized` if that's what you wanted. However, it looks like Slonik [itself](https://github.com/gajus/slonik/blob/fc7739d41ca9626ddde9cdb701a808a857435b0c/src/factories/createPoolConfiguration.ts#L31-L36) specifies `false` for `rejectUnauthorized` when SSL is specified. (Maybe because that [seems](https://node-postgres.com/announcements#2020-02-25) to have been the default at one point?) That means that without additional configuration, Slonik and Knex will use different values for `rejectUnauthorized` when SSL is specified. But maybe that's OK — is the worst case just that Knex throws an error when Slonik doesn't? If Knex throws an error, a couple of connection string query parameters that might be helpful are `sslmode=no-verify` (a [`pg-connection-string`](https://github.com/brianc/node-postgres/tree/master/packages/pg-connection-string) feature) and `sslrootcert`. (`pg` also has a couple of [options](https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#pg810) similar to `sslmode=no-verify`: `ssl=no-verify` and `PGSSLMODE=no-verify`. `ssl=no-verify` probably won't work, because Slonik seems to use `pg-connection-string` to parse the connection string, so `ssl=no-verify` won't make it all the way to `pg`. Using the `PGSSLMODE` environment variable might be an option, but I think that'd require changes to our Docker setup. And `sslmode=no-verify` was introduced more recently than these `pg` options.) Related Slonik issue: gajus/slonik#159

**Comment by florianm** [comment]
FYI, a quick write-up of working and breaking configs plus use case of DB with TLS/SSL: https://forum.getodk.org/t/odk-central-with-custom-database-with-ssl/34435/15
