### ISSUE TITLE
Form preview tasks unexpectedly stop running

### ISSUE THREAD

**Issue by yanokwa** [getodk/central-backend#388]
I've seen this issue on two servers now. Users report that the preview buttons are not enabled. 

An investigation of the service logs show that `start/finish processing event` are not present in the logs. A `docker-compose stop && docker-compose up -d` fixes it and the logs then immediately show the correct events.

Both servers are running v1.2.x, but I don't know if this is a regression. I haven't looked closely, but this doesn't seem associated with a big spike in CPU/RAM or anything like that.

**Comment by matthew-white** [comment]
@yanokwa, can you tell whether the fix for v1.4 resolved this issue? If it's unclear, maybe we close for now and reopen if something comes up?

**Comment by yanokwa** [comment]
I haven't experienced the problem recently, so I think it's safe to close for now.
