### ISSUE TITLE
Non-ASCII characters in Content-Disposition header

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#389]
A report on the forum notes that downloading a submission attachment whose filename contains a non-ASCII character results in an error: https://forum.getodk.org/t/error-with-non-ascii-chars-in-attachment-filenames/34462

This has come up [before](https://github.com/getodk/central-backend/pull/332#discussion_r582181433). However, `sanitize()` was added to our `binary()` function to address this: https://github.com/getodk/central-backend/pull/332/commits/c1e41baefe570d4af64f69de3f9f13c07068667f

The endpoint to download a submission attachment uses the `binary()` function. However, while `binary()` does call `sanitize()`, it looks like `sanitize()` doesn't remove non-ASCII characters.

If a change is needed in `binary()`, I think it'd also be needed elsewhere, as there are places outside `binary()` where we use `sanitize()` together with `Content-Disposition`.

Somewhat relatedly, I'm noticing that we don't call `binary()` or `sanitize()` for the endpoint to download a form attachment:

https://github.com/getodk/central-backend/blob/78833c1f10092c66176fe83337355ddbc683cdd4/lib/resources/forms.js#L208-L221

Would it work to specify a `filename*` parameter to `Content-Disposition` in addition to `filename`? Does Express or an existing npm package provide an easy way to specify both parameters?

**Comment by matthew-white** [comment]
Just saw [this](https://sentry.io/organizations/getodk/issues/2563526531/?project=1298632) Sentry issue, which seems related. In this case, it looks like the .csv.zip can't be downloaded, because the form ID contains a Unicode character.

**Comment by matthew-white** [comment]
This Sentry issue also seems related: https://sentry.io/organizations/getodk/issues/2572098274/?project=1298632

**Comment by issa-tseng** [comment]
@matthew-white can you look over my work here? https://github.com/getodk/central-backend/pull/395/commits/086a59b9f583a18d599911344991c347c4f0c582
the rfcs are very very very very confusing.
