### ISSUE TITLE
Add form version to submissions CSV and OData

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#398]
It looks like some users are using an XPath expression in order to store the form version as a form field, in order to access the form version during later data management/analysis: https://forum.getodk.org/t/tracing-the-propagation-of-different-versions-of-same-form/34824/3. I think it'd be helpful if we automatically added the form version as a column in the submissions CSV file and as a property in the OData response. There wouldn't be filtering on form version (form version isn't a column on the `submissions` table, so I think it might be hard to add filtering).

I don't remember whether a single submission can be associated with multiple form versions (if the submission is edited). When we export submissions, we export the latest submission version, so I think we should use the form version associated with the latest submission version (then probably document that in the API docs).

**Comment by issa-tseng** [comment]
it can probably be joined and filtered.

a single submission is no associated with any form versions, only submission versions are.

**Comment by matthew-white** [comment]
Closed by #432. I don't think we added the ability to filter on form version, but that's something we could do later if need be.
