### ISSUE TITLE
Can a request change the database after the response?

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#407]
This question came up as I was looking into #381, but I think is a more general question. While looking into #381, I observed the following:

- Use Frontend to try to create a new form in a project.
- The request timed out (we'll look into why as part of #381). A 504 response was returned and displayed in Frontend.
- However, when querying `pg_stat_activity`, there seemed to be related queries still active.
- And about an hour later, the form was actually created and became visible in the project.

I think Marzena noticed something similar. From the QA document (v1.3, item 1):

> I tried to add few different forms and every time I saw this error. I tried to add forms to the existed project and new project with the same result. It takes a long time before Central shows this error.

> When I returned to the project after a long while forms were visible!

Does that mean that it's possible for a request to have an effect on the database after an error response has been returned for the request? That would feel surprising to me. Then again, presumably everything is still being run in a transaction, so the changes from the request will be committed only if they don't conflict with later transactions.

I think the default value of `statementTimeout` in Slonik is 60 seconds, which is another reason why it seems surprising that a request could have an effect on the database after the response times out.

It might not be worth spending too much time looking into these questions. If we know that something is leading to response timeouts, that something is probably the more useful focus, because if responses never time out, this question becomes moot. However, it'd be interesting to learn how things are expected to behave here!

**Comment by issa-tseng** [comment]
you're forgetting that nginx exists.  the 504 comes from nginx getting impatient and giving up on central-backend. but depending on the state of the backend, the request is not always cancelled in time to prevent it from completing.
