### ISSUE TITLE
Warn if new form definition has structural change

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#439]
Deleting a form field can add complications to a data analysis workflow, because the user may still need to access the data from the deleted field. This comes up in particular when a user tries to rename a field or moves a field into or out of a group, because Backend understands that as two operations: the deletion of the old field and the addition of a new field.

In v1.4, we are adding the ability to include deleted fields in the submissions export. @yanokwa has suggested for a later release that we also warn the user if they upload a form definition that deletes a field. The text of the warning would point to the docs. The user experience would be similar to how warnings are currently shown for an XLSForm. One tricky case to consider is if an uploaded form definition generates XLSForm warnings and also deletes a field: how do we return both sets of warnings from Backend?

Related Forum topic: https://forum.getodk.org/t/data-loss-scare-when-updating-to-a-new-form-version/39777

**Comment by matthew-white** [comment]
@yanokwa, you mentioned showing a warning about structural changes to the form. Are there structural changes other than field deletion that should result in a warning? If the user adds a field but doesn't delete a field, no warning should be shown, right?

**Comment by yanokwa** [comment]
Adding a field should not trigger a warning. It's only deletion (direct or indirect through renaming).

**Comment by lognaturel** [comment]
Here's a user describing the current experience: https://forum.getodk.org/t/data-loss-scare-when-updating-to-a-new-form-version/39777/2

**Comment by dbemke** [comment]
A user is unable to publish a draft version of o form with a deleted field. After clicking the “proceed” button the dialog is shown again.
In the warning there is “?ignoreWarnings=true”



![Image](https://user-images.githubusercontent.com/56479916/214815905-1050b8b7-446a-4ba6-b378-5ef749139a4c.png)

**Comment by srujner** [comment]
Does deleting the whole Column form the xml file should also trigger a warning, because right now it doesn't?

**Comment by matthew-white** [comment]
> A user is unable to publish a draft version of o form with a deleted field.

This should be resolved now.

> Does deleting the whole Column from the xml file should also trigger a warning, because right now it doesn't?

A warning should be shown whether the user uploads an XLSForm or an XML XForm. Is that what you mean? If you have an example that would be easy to share, it'd be helpful to see what file you're trying.

**Comment by matthew-white** [comment]
> Does deleting the whole Column from the xml file should also trigger a warning, because right now it doesn't?

Just to clarify, a warning should be shown whenever a field is deleted, whether in an XLSForm or an XML XForm. If you're deleting a field in the XML XForm, you'll need to delete it everywhere within the XML, including the instance.

**Comment by dbemke** [comment]
Tested with success!
