### ISSUE TITLE
Minimum Node Version should be 14

### ISSUE THREAD

**Issue by devasyadave** [getodk/central-backend#442]
make
node -e 'const { withDatabase, migrate } = require("./lib/model/migrate"); withDatabase(require("config").get("default.database"))(migrate);'
(node:265432) UnhandledPromiseRejectionWarning: /home/ubuntu/odk-central/central-backend/lib/data/schema.js:408
    for (end = idx + 1; as[end]?.path.startsWith(subtreePrefix); end += 1);
                                ^

SyntaxError: Unexpected token '.'

Above error occurs due to '?' not supported in Node versions older than 14. Documentation mentions to install Node version 12. This should be changed to minimum Node version 14

**Comment by matthew-white** [comment]
Thanks for noting this, @devasyadave! I think you're right that the code currently requires Node 14. We'll try to update the readme soon.
