### ISSUE TITLE
Form titles with `&` not decoded properly

### ISSUE THREAD

**Issue by yanokwa** [getodk/central-backend#478]
If you put an `&` in the XLSForm title, Central’s UI/DB shows `&amp;` while Enketo and Collect show the correct `&`.

*xlsform*
<img width="223" alt="xlsform" src="https://user-images.githubusercontent.com/32369/166971046-bfa4aabc-dc44-464e-b093-61f82a302454.png">

*central ui (and db)*
<img width="298" alt="central" src="https://user-images.githubusercontent.com/32369/166971043-370d0c2d-b14f-428b-a2dd-72b77c2e280c.png">

*xml*
<img width="282" alt="Screen Shot 2022-05-05 at 09 42 21" src="https://user-images.githubusercontent.com/32369/166971883-46516d65-4bbd-4b51-ad33-f51189055485.png">

*enketo*
<img width="288" alt="enketo" src="https://user-images.githubusercontent.com/32369/166971040-db4a96c0-56fb-4b07-966e-3c5f910682c5.png">

@matthew-white says...
> Frontend just uses what it gets from the API, so I think it’d be an issue on central-backend. We probably just need to decode the text after we extract it from the XML.

If we don't already have tests, it'd also be good to add some tests for Unicode characters. 

Potentially relevant: I vaguely remember that HTML documents don't support Unicode in the `<title>` tag.

**Comment by matthew-white** [comment]
I wonder what the best place to do this decoding would be. We could do it in `Form.fromXml()` as a one-off change. But if we almost always want the decoded value in other cases as well, maybe it'd make sense to make this change in the `text()` XML utility function instead?
