### ISSUE TITLE
Handle ConnectionError thrown by Slonik stream()

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#479]
The Slonik [`stream()`](https://github.com/gajus/slonik#stream) method takes a `sql` string and a callback. The callback will be passed the stream. `stream()` returns a promise that seems to be resolved once the stream ends and rejected if there's an error. Looking at our `stream()` decorator that we use in query modules, it looks like we don't really care about that resolve case. That is, all our logic will happen in the callback, with the stream rather than with the promise:

https://github.com/getodk/central-backend/blob/d71a438f6c4ca823e46977481d26abc2a22ebd6b/lib/util/db.js#L239

However, I think we may want to do more to account for the case in which the promise is rejected. That can happen if the database connection pool is full and `stream()` is unable to acquire a connection. In that case, it looks like Slonik never calls the callback, which means that our decorator will return a promise that never settles.

I think I'm able to reproduce that as follows. First, add a simple use of `stream()` to the `Submissions` query module:

```js
const streamCount = () => ({ stream }) =>
  stream(sql`select count(*) from submissions`);
```

Next, add an endpoint that will call this `Submissions.streamCount()` method only after filling up the connection pool. When I send a request to this endpoint, I never get a response (not even an error).

```js
service.get('/repro', endpoint(async ({ db, Submissions }) => {
  console.log('attempting to make 10 connections');
  let release = false;
  const p = new Promise(resolve => {
    const checkRelease = () => {
      if (release)
        resolve();
      else
        setTimeout(checkRelease, 500);
    };
    checkRelease();
  });
  for (let i = 0; i < 10; i += 1)
    db.connect(() => p);

  // Wait a few seconds so that the 10 connections above can be acquired.
  console.log('waiting for 5 seconds');
  await new Promise(resolve => { setTimeout(resolve, 5000); });

  console.log('running streamCount()');
  await Submissions.streamCount();
  console.log('success');

  release = true;
  return { success: true };
}));
```

This is the resulting log:

```
attempting to make 10 connections
waiting for 5 seconds
running streamCount()
(node:40096) UnhandledPromiseRejectionWarning: ConnectionError: timeout exceeded when trying to connect
    at Object.createConnection (central-backend/node_modules/slonik/dist/src/factories/createConnection.js:54:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:40096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I think the `UnhandledPromiseRejectionWarning` comes from the fact that we don't catch the promise returned by the Slonik `stream()` method.

I'm not quite sure what the right answer is here. Given the way we use streams within `Promise.all()`, I don't think we can return a promise that only resolves once the Slonik promise resolves. However, in the case that the Slonik promise is rejected before the callback is called, I think we should return a rejected promise: that should solve the issue of the promise never settling. I also think we should catch the promise from the Slonik `stream()` method.

**Comment by alxndrsn** [comment]
Another approach to recreating this is to hammer the right endpoint.

For me, the following will both reliably recreate the `UnhandledPromiseRejectionWarning`:

### odata

```
siege http://localhost:8989/v1/projects/149/forms/Survey.svc/Submissions \
    --header "Authorization: Basic $(echo -n "${ODK_USER_EMAIL}:${ODK_USER_PASSWORD}" | base64)"
```

### csv

```
siege 'http://localhost:8989/v1/projects/149/forms/Survey/submissions.csv?splitSelectMultiples=false&groupPaths=true&deletedFields=false' \
    --header "Authorization: Basic $(echo -n "${ODK_USER_EMAIL}:${ODK_USER_PASSWORD}" | base64)"
```
