### ISSUE TITLE
Sentry errors without server_name

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#483]
We're seeing errors in Sentry that don't indicate a `server_name`, for example, [this](https://sentry.io/organizations/getodk/issues/2423174952/?environment=production) error from an ODK Cloud server. Because the error doesn't indicate things like the request URL, I'm thinking that it was thrown by the worker mechanism. I think our hope was that 9e410332ed4e65ab36c87b09c8ee8ce54937c3ad would resolve this, but it seems like these errors are still appearing in Sentry.

**Comment by yanokwa** [comment]
For the record, I'm not optimistic that #521 solves this problem. 

The only tags on see on this type of error is `environment`, `handled`, `level`, and `mechanism`. I see a lot more tags on other errors (e.g., `runtime`, `url`, `device`). 

I'm out of my depth here, but it would seem that perhaps workers don't have access to the full Sentry env? @matthew-white would it be worth it to escalate to their support team?

**Comment by matthew-white** [comment]
I also don't think that #521 solves this problem. For some of the tags you mentioned, I think it's expected that those are missing for workers, because there's no associated request (for example, `url`). But in other cases, it seems pretty surprising that the tag is missing (for example, `runtime`). I'm not sure, but it looks like this might be fixed in the latest version of the Sentry SDK: see getsentry/sentry-javascript#5190 (search for `server_name`).

**Comment by matthew-white** [comment]
For posterity, note that #626 effectively reverted the commit 9e410332ed4e65ab36c87b09c8ee8ce54937c3ad mentioned in the issue description.
