### ISSUE TITLE
OData: Can't request table if repeat group name isn't valid OData name

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#496]
ODK field names might not be valid OData names, so we sanitize field names for OData. However, I think I'm seeing that if the name of a repeat group isn't a valid OData name, it's not possible to request the table for the repeat group. For example, I've uploaded a form ([`odata_sanitize_repeat_name`](https://test.getodk.cloud/#/projects/388/forms/odata_sanitize_repeat_name)) with a repeat group named `q1.8`. If I request either https://test.getodk.cloud/v1/projects/388/forms/odata_sanitize_repeat_name.svc/Submissions.q1_8 or https://test.getodk.cloud/v1/projects/388/forms/odata_sanitize_repeat_name.svc/Submissions.q1.8, a 404.1 Problem is returned. I think that's because `verifyTablePath()` verifies against the original field name, not the sanitized OData name:

https://github.com/getodk/central-backend/blob/bdc73e91be2529242b5518b5c16c5c559ffefec1/lib/formats/odata.js#L336
https://github.com/getodk/central-backend/blob/bdc73e91be2529242b5518b5c16c5c559ffefec1/lib/formats/odata.js#L79-L90

Relatedly, if I request https://test.getodk.cloud/v1/projects/388/forms/odata_sanitize_repeat_name.svc/Submissions, I see:

```json5
{
  "value": [
    {
      "__id": "uuid:bf17f620-c56a-4533-8f89-da3f5c9bf37a",
      "meta": {
        "instanceID": "uuid:bf17f620-c56a-4533-8f89-da3f5c9bf37a"
      },
      "__system": {
        // ...
      },
      "q1_8@odata.navigationLink": "Submissions('uuid%3Abf17f620-c56a-4533-8f89-da3f5c9bf37a')/q1.8"
    }
  ],
  "@odata.context": "https://test.getodk.cloud/v1/projects/388/forms/odata_sanitize_repeat_name.svc/$metadata#Submissions"
}
```

Here `q1_8@odata.navigationLink` ends with `/q1.8`, but I'd expect the sanitized `/q1_8`.

I think the same issues come up if the field name of the repeat group is a valid OData name, but the field name of a group in which the repeat group is nested isn't a valid OData name.

**Comment by dbemke** [comment]
Tested with success!

**Comment by srujner** [comment]
Tested with success!
