### ISSUE TITLE
Comment submission response format is bizarre

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#516]
### Request

```bash
curl 'https://example.com/v1/projects/1/forms/some_form/submissions/uuid%3A3c4b658c-12f0-48c9-a22d-cec305be99a0/comments' \
    ...auth headers etc... \
    --data-raw $'{"body":"hi"}'
```

### Response

```json
{"id":{},"submissionId":{},"actorId":{},"body":{"0":"h","1":"i"},"createdAt":{}}
```

**Comment by matthew-white** [comment]
Definitely quite bizarre! Weird that properties that are normally numeric are empty objects in the response. Also odd that `body`, which should be a string, has been converted to an array-like object. It's actually surprising to see `submissionId` in there at all, as I don't believe we intend to expose that over the API.

This is the response to a POST request, right? Does the response to GET &hellip;/comments look normal?

**Comment by alxndrsn** [comment]
> This is the response to a POST request, right?

Yes :+1: 

> Does the response to GET …/comments look normal?

Yes :slightly_smiling_face:

**Comment by issa-tseng** [comment]
https://github.com/getodk/central-backend/blob/master/lib/model/query/comments.js#L18 well it looks like it's trying. maybe that `map` should not be there.

**Comment by alxndrsn** [comment]
```
> JSON.stringify({ ...[ ...'hello' ] })
'{"0":"h","1":"e","2":"l","3":"l","4":"o"}'
```
:shrug:

**Comment by matthew-white** [comment]
> maybe that `map` should not be there.

That sounds quite plausible to me! That would explain why every property of the object is converted to an object (probably to a `Comment` specifically), as well as why certain properties aren't removed.

**Comment by issa-tseng** [comment]
typically you'd only need to map there if the result is uncertain, but w this query it isn't so. makes sense it shouldn't be there.

**Comment by matthew-white** [comment]
@alxndrsn, if you have time, would you be up for seeing whether removing `map()` resolves this issue?

**Comment by alxndrsn** [comment]
@matthew-white removing `map()` doesn't seem to break anything, except the order of a CSV...

**Comment by alxndrsn** [comment]
...it also seems to make the response more reasonable, e.g.

```
$ curl 'example.com/v1/projects/481/forms/250_questions/submissions/uuid%3Ad82377cb-6601-4320-b8f2-d24be1e1e817/comments'\
    ...
    --data-raw '{"body":"hello, normality"}'
{"body":"hello, normality","actorId":17059,"createdAt":"2022-07-28T14:44:14.479Z"}
```

I'll open a PR for this, but as the response's `.body` is obviously never used, maybe it doesn't matter?

**Comment by matthew-white** [comment]
Yay, that response looks much better! And yeah, this issue probably isn't super high-priority, but especially if we know the solution, I think it'd be nice to fix.
