### ISSUE TITLE
Uniquely identify servers in Sentry

### ISSUE THREAD

**Issue by yanokwa** [getodk/central-backend#521]
There are certain self-hosted servers we support that have known problems (e.g., premature close). In the Sentry UI, we typically ignore these errors, but it would be better if we could ignore them per server (or in Sentry terminology, per user) so we are alerted when new servers have the problem.

https://docs.sentry.io/platforms/javascript/enriching-events/identify-user/ suggests that we can add an internal identifier for the user. I would propose we use the Docker hostname of the service because it is randomly generated and unique (e.g., `3154baf7bA72`) on servers we don't support and explicitly set on servers (`nafundi-01`) we do support.

**Comment by matthew-white** [comment]
Right now, `server_name` is sometimes set in Sentry and sometimes not (for example, #483). When `server_name` is set, I believe it's the Docker hostname, right? If we found a way to consistently set `server_name`, would that also work? It looks like you can filter on `server_name` within Sentry.

**Comment by yanokwa** [comment]
Yes, `server_name` is the Docker hostname. Setting it consistently would be helpful for sure, but I think that's a separate issue. What I'm asking about in this issue is to be able to ignore an issue until it affects $n users or an additional user.

**Comment by matthew-white** [comment]
Closed by #593.
