### ISSUE TITLE
Test failure causes subsequent test to time out

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#541]
Specifically the failure demonstrated in https://github.com/getodk/central-backend/pull/540, but I suspect there are other instances of the same.

**Comment by matthew-white** [comment]
What stood out to me in #532 was that a database table didn't exist. For example:

```
  2) task: accounts
       createUser
         should create a user account:
     error: relation "actees" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

Looking at test/integration/setup.js, I suspect that it has something to do with `reinit()`, which calls `initialize()`, which drops the database before recreating it. `reinit()` doesn't return a promise, so my guess is that Mocha isn't waiting for `initialize()` to finish its work before proceeding to the next test.

**Comment by matthew-white** [comment]
> my guess is that Mocha isn't waiting for initialize() to finish its work

Or maybe that's not it. Maybe `reinit()` is being run after the first test finally completes, after Mocha has moved on to the second test due to the timeout of the first test.

**Comment by alxndrsn** [comment]
The problem seems to be in the callback for `zipStreamToFiles()`.  If a `should.js` assertion fails inside the callback, an error will be thrown.  There is currently no handling for this, so the wrapping promise will never resolve.  This probably means the `reinit()` callback will only be triggered when the test times out, which may be after the subsequent test(s) has already started.

https://github.com/getodk/central-backend/blob/master/test/integration/api/submissions.js#L1483-L1500

**Comment by matthew-white** [comment]
I still think there are interesting questions surrounding `reinit()`, but we can also circle back to those later. Note that `reinit()` is only called by `testServiceFullTrx()` and `testContainerFullTrx()`, not `testService()` or `testContainer()`. The tests in #530 use `testService()`, so they shouldn't be affected by `reinit()`.

**Comment by alxndrsn** [comment]
@matthew-white I think the root issue is basically that `reinit()` is called from within tests, rather than in a mocha `after()`/`afterEach()` function, which means that the time taken by `reinit()` will be considered part of the main test timeout.

**Comment by issa-tseng** [comment]
> I think the root issue is basically that `reinit()` is called from within tests, rather than in a mocha `after()`/`afterEach()` function

this makes sense
