### ISSUE TITLE
Add version information to Sentry to identify versions

### ISSUE THREAD

**Issue by yanokwa** [getodk/central-backend#547]
"I would love to send Sentry the Central version somehow so that we can filter on that. There are so many non-Cloud users on previous versions of Central, so most Sentry errors seem to be noise."
– @matthew-white 

I believe this can be as simple as setting the environment and release identifier
* https://docs.sentry.io/platforms/javascript/configuration/environments/
* https://docs.sentry.io/platforms/javascript/configuration/releases/#setting-a-release

Related: #521

**Comment by matthew-white** [comment]
This issue has been closed, but we're tracking a related bug at getodk/central#335.
