### ISSUE TITLE
db.stream() has no timeout

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#565]
Currently there is no timeout on database stream connections.

This can be observed by patching https://github.com/gajus/slonik/issues/347 and then creating a large number of slow, streamed connections (e.g. submission zip export), until central-backend stops responding to requests.  You can check for open connections in postgres with `SELECT COUNT(*) FROM pg_stat_activity;`.

This _may_ be because the [version of Slonik currently in-use](https://github.com/getodk/central-backend/blob/f391b6c65bd94b99fbf7f01ed69b071ff296f48a/package-lock.json#L5996-L5997) [has various timeout settings disabled](https://github.com/gajus/slonik/blob/v23.6.0/src/factories/createPoolConfiguration.ts).

Slonik does not appear to implement its own stream timeout functionality.

It [seems like](https://github.com/gajus/slonik/blob/v23.6.0/src/QueryStream.ts#L14) slonik streams use [`pg-cursor`](https://github.com/brianc/node-postgres/tree/pg-cursor%402.7.3/packages/pg-cursor) under the hood, which may use [postgres cusrors](https://www.postgresql.org/docs/9.6/plpgsql-cursors.html).  I haven't found clear documentation of how/if postgres cursors are timed out.  However, when the lockup occurs there are clear, relevant entries in both `pg_stat_activity` and `pg_locks`, but there are no rows returned by `SELECT * FROM pg_cursors;`.  This may mean that PostgreSQL Cursors are not actually being used.

Timeouts might not be necessary if central-backend reliably destroys streams in all code paths.  It's hinted this may not be the case at https://github.com/getodk/central-backend/blob/master/lib/resources/submissions.js#L282.  Either way, it might be pragmatic to add timeout handling in `lib/util/db.js`.

Related:

* https://github.com/brianc/node-postgres/issues/2103
* https://github.com/gajus/slonik/issues/347
* https://github.com/getodk/central-backend/issues/485
* https://github.com/getodk/central-backend/issues/482

**Comment by issa-tseng** [comment]
yeah, the current intended mechanism is that the client timeout will terminate all active queries, not just streams. of course, if the client decides to never time out that’s a problem but i think nginx will in most cases.

**Comment by matthew-white** [comment]
> if the client decides to never time out that’s a problem but i think nginx will in most cases.

From what I've seen, the nginx timeout doesn't have an effect on Backend: it doesn't actually terminate active queries. For example, if you send a non-GET request, and the nginx timeout kicks in, then the client will receive an error response; but Backend will continue working on the request. That means that despite the error response, the request may ultimately have its intended effect.

**Comment by alxndrsn** [comment]
> From what I've seen, the nginx timeout doesn't have an effect on Backend: it doesn't actually terminate active queries.

I'm observing the same.

> if you send a non-GET request, and the nginx timeout kicks in, then the client will receive an error response; but Backend will continue working on the request

@matthew-white is the behaviour different for `GET` requests?

**Comment by matthew-white** [comment]
> is the behaviour different for `GET` requests?

I only remember seeing this for non-GET requests, but I would guess that it's the same for GET requests.

**Comment by matthew-white** [comment]
Closed by #604.
