### ISSUE TITLE
Update sentry URL

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#584]
See: https://github.com/getodk/central/issues/311

The change to `central-backend` will either need to be done in tandem with `central`, or in a backwards-compatible way, e.g.:

```js
const dsn = config.orgSubdomain ?
    `https://${config.key}@${config.orgSubdomain}.ingest.sentry.io/${config.project}`
    `https://${config.key}@sentry.io/${config.project}`;
```

**Comment by matthew-white** [comment]
Closed by #585.
