### ISSUE TITLE
REST GET .../submissions should return `instanceName` or update API docs

### ISSUE THREAD

**Issue by sadiqkhoja** [getodk/central-backend#590]
Currently REST endpoint `GET forms/id/submissions` doesn't return `instanceName`, we need to fix that or update API docs where we say that `instanceName` is only supported for ODATA endpoints

```
curl 'https://test.getodk.cloud/v1/projects/390/forms/Simple/Submissions' -H  ...

Response:
[
    {
        "instanceId": "uuid:08349870-0941-4a7c-8843-11fdd9a70908",
        "submitterId": 17150,
        "deviceId": null,
        "createdAt": "2022-08-30T15:34:22.162Z",
        "updatedAt": null,
        "reviewState": null
    }
]
```

REF: https://forum.getodk.org/t/odk-central-api-not-returning-instancename-of-submission/38729/6

**Comment by matthew-white** [comment]
`instanceName` is also available using the REST API endpoints for a submission's versions or for a particular submission version. I think this relates to #481: the API distinguishes between submissions and submission versions (the two return different data), but the API docs don't always reflect that.
