### ISSUE TITLE
Error handler may cause unhandledPromiseRejection()

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#592]
```
TypeError: Cannot read property 'isProblem' of undefined
  File "/usr/odk/lib/http/endpoint.js", line 194, in defaultErrorWriter
    if (error.isProblem === true) {
  File "/usr/odk/lib/http/endpoint.js", line 162, in null.<anonymous>
    errorWriter(err, request, response);
  ?, in runMicrotasks
  ```

Possibly caused by calls to enketo/api/v2/survey.

**Comment by matthew-white** [comment]
I wanted to link to Sentry issues where we've seen this error:

- https://sentry.io/organizations/getodk/issues/3547312212
- https://sentry.io/organizations/getodk/issues/3547397413

The breadcrumbs there include the Enketo endpoint that @alxndrsn mentioned.

I'm not sure, but I think this might be an issue in `defaultErrorWriter()` (at least in part). Elsewhere there seems to be logic that implies the possibility that the error variable may be `null`:

https://github.com/getodk/central-backend/blob/87aedb0b58973d7454ddd3a543fad7547646bcdd/lib/http/endpoint.js#L159-L162
https://github.com/getodk/central-backend/blob/87aedb0b58973d7454ddd3a543fad7547646bcdd/lib/http/service.js#L88-L94
https://github.com/getodk/central-backend/blob/87aedb0b58973d7454ddd3a543fad7547646bcdd/lib/http/endpoint.js#L248-L251
https://github.com/getodk/central-backend/blob/87aedb0b58973d7454ddd3a543fad7547646bcdd/lib/http/endpoint.js#L309-L312

However, `defaultErrorWriter()` doesn't have logic around that case:

https://github.com/getodk/central-backend/blob/87aedb0b58973d7454ddd3a543fad7547646bcdd/lib/http/endpoint.js#L193-L194

For example, above, `openRosaErrorWriter()` and `odataXmlErrorWriter()` call `defaultErrorWriter()` when `error` is `null`, but then `defaultErrorWriter()` isn't able to process that case.

**Comment by alxndrsn** [comment]
> I think this might be an issue in defaultErrorWriter() (at least in part)

Agreed - I don't think the error handler should be generating new errors, even if it's called with bad data!
