### ISSUE TITLE
Entity type of repeats with hyphens cannot be resolved from metadata in OData feed

### ISSUE THREAD

**Issue by yanokwa** [getodk/central-backend#607]
If you have a repeat that has a hyphen in the name, you get this error in Power BI. 
> Cannot get feed for 'Submissions.r-1' as we could not resolve its entity type from metadata

<img width="875" alt="Screen Shot 2022-09-14 at 16 27 30" src="https://user-images.githubusercontent.com/32369/190280212-28c2780e-329b-4e48-b108-9dccbce477c6.png">

**Service document**
https://test.getodk.cloud/v1/projects/102/forms/bug.svc with the header (Accept:application/json)
```json
{
   "@odata.context":"https://test.getodk.cloud/v1/projects/102/forms/bug.svc//$metadata",
   "value":[
      {
         "name":"Submissions",
         "kind":"EntitySet",
         "url":"Submissions"
      },
      {
         "name":"Submissions.r-1",
         "kind":"EntitySet",
         "url":"Submissions.r-1"
      }
   ]
}
```

**Metadata document**
https://test.getodk.cloud/v1/projects/102/forms/bug.svc/$metadata
```xml
<EntityType Name="Submissions.r_1">
	<Key>
		<PropertyRef Name="__id"/>
	</Key>
	<Property Name="__id" Type="Edm.String"/>
	<Property Name="__Submissions-id" Type="Edm.String"/>
	<Property Name="t_3" Type="Edm.String"/>
</EntityType>
```

**Parent data document**
https://test.getodk.cloud/v1/projects/102/forms/bug.svc/Submissions with the header (Accept:application/json)
```json
{
   "value":[
      {
         "__id":"uuid:c2858e84-349b-420d-a25e-1e6978339759",
         "t_1":"A",
         "t_2":"B",
         "meta":{
            "instanceID":"uuid:c2858e84-349b-420d-a25e-1e6978339759"
         },
         "__system":{
            "submissionDate":"2022-09-14T23:26:18.944Z",
            "updatedAt":null,
            "submitterId":"15415",
            "submitterName":"yanokwa@getodk.org",
            "attachmentsPresent":0,
            "attachmentsExpected":0,
            "status":null,
            "reviewState":null,
            "deviceId":null,
            "edits":0,
            "formVersion":""
         },
         "r_1@odata.navigationLink":"Submissions('uuid%3Ac2858e84-349b-420d-a25e-1e6978339759')/r-1"
      }
   ],
   "@odata.context":"https://test.getodk.cloud/v1/projects/102/forms/bug.svc/$metadata#Submissions"
}
```

**Child data document**
https://test.getodk.cloud/v1/projects/102/forms/bug.svc/Submissions.r-1 with the header (Accept:application/json)

```json
{
   "value":[
      {
         "t_3":"C",
         "__id":"7f33afe2630d5906c07c7ac50d3395a0cae6e2fe",
         "__Submissions-id":"uuid:c2858e84-349b-420d-a25e-1e6978339759"
      },
      {
         "t_3":"D",
         "__id":"39931f4efe375f7d0b47487a71e700b812ed1f94",
         "__Submissions-id":"uuid:c2858e84-349b-420d-a25e-1e6978339759"
      }
   ],
   "@odata.context":"https://test.getodk.cloud/v1/projects/102/forms/bug.svc/$metadata#Submissions.r-1"
}
```

Note that the service document has `Submissions.r-1` but the metadata document has `Submissions.r_1`. That's a mismatch. 

@lognaturel says that OData doesn't support hyphens which is why they are replaced in the metadata document. I believe the bug here is that they should also be replaced in the service document.

XLSForm: [bug.xlsx.zip](https://github.com/getodk/central-backend/files/9570575/bug.xlsx.zip)

**Comment by matthew-white** [comment]
Just wanted to mention #496, which I think has a lot of overlap. I didn't look at the service document as part of #496, so it's helpful to know that the names of repeat groups aren't sanitized for OData there. One thing that's interesting is that you were able to request the child data document, while I wasn't able to in #496. I'm guessing that's because my example had a period, while yours has a hyphen.

**Comment by srujner** [comment]
Tested with Success!
