### ISSUE TITLE
Add xlsFormId flag to purge-forms.js

### ISSUE THREAD

**Issue by yanokwa** [getodk/central-backend#652]
Related to #487, it'd be nice to purge via xmlFormId because that's what is most visible to users. It's kinda annoying to have to log into the DB to find the specific form ID. 
See https://forum.getodk.org/t/re-creating-identically-named-form-version-after-deletion-on-odk-central/39405

xmlFormIds are not unique, so this command could purge multiple forms. I'd bias to requiring a projectId for this command to add to the safety.

**Comment by matthew-white** [comment]
> It's kinda annoying to have to log into the DB to find the specific form ID.

The API will return the numeric form ID for deleted forms. If you request &hellip;/forms?deleted=true, that should return numeric IDs that you can use to purge.
