### ISSUE TITLE
Inform user about failure to process submission for entities

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#661]
For after v2022.3:

When a submission is approved, the worker job `createEntityFromSubmission` calls `Entities.processSubmissionDef()`, which checks whether the submission creates a new entity and tries to create the entity if so. `Entities.processSubmissionDef()` can return a rejected promise for a variety reasons. If there's a user error (for example, invalid XML), then `Entities.processSubmissionDef()` will generally reject with an `entityViolation` Problem. In that case, the job logs an `entity.create.error` audit log entry and marks the submission as having been processed. The `entity.create.error` will be returned to the user over the API and shown in Frontend. However, `Entities.processSubmissionDef()` can also be rejected for other reasons, for example, if there's an error connecting to the database. In that case, the job won't log an `entity.create.error` audit log entry and will just fail. That's intentional, because in that case, we want Backend to try the job again. However, if the job fails enough times, then Backend will stop trying. In that case, it's possible that an entity should have been created, but won't be — and there's no indication of that to the user. The user isn't able to detect that case in Frontend or over the API.

I think we should account for that case somehow:

- Maybe the job should check whether it's on its last try. In that case, if `Entities.processSubmissionDef()` is rejected, then the job should log an `entity.create.error` audit log entry no matter what the reason for the rejection was.
- Or maybe we should separately list to the user all `submission.update` audit log entries that haven't been successfully processed for entities (failed too many times, the job hasn't been tried yet, etc.).

**Comment by ktuite** [comment]
We changed the entity processing mechanism in this PR(https://github.com/getodk/central-backend/pull/685) since this issue was created. The only other entity problem we saw after release was addressed in #742.

I'm going to close this issue now. When we have more entity-processing errors (maybe when we get to updates) we will have to revisit a lot of things about entity errors, events, and audit logs anyway.
