### ISSUE TITLE
Makes changes to dataset-related logging in audit log

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#664]
For after v2022.3 — moving from https://github.com/getodk/central-backend/issues/649#issuecomment-1308327816:

Backend logs `dataset.create` and `dataset.update` in the audit log. However, I think that there are a couple of possibilities for confusion there:

- The events are logged too early.
- The events are logged too frequently.

More specifically:

- If you upload but don't publish a form definition that would create entities for a new dataset, then `dataset.create` is immediately logged, even if the form draft is ultimately abandoned and the dataset never becomes visible on the project.
- If you upload but don't publish a form definition that would add a property to an existing dataset, then `dataset.update` is immediately logged, even if the form draft is ultimately abandoned and the property never becomes visible on the dataset. (Maybe related to https://github.com/getodk/central-backend/issues/649#issuecomment-1309167680?)
- `dataset.update` is logged even when there are no new properties. It is logged when a form definition is uploaded that would create entities for an existing dataset, not when that form definition would add a property to the dataset.

I'd expect `dataset.create` and `dataset.update` to be logged only when the form draft is published. I know that creating a draft can have an immediate effect on the `datasets` table, and I think it makes sense that it works that way under the hood. But I think we're exposing those mechanics over the audit log in a way that could be surprising and that ultimately makes the audit log less actionable. It also results in a mismatch between what's in the audit log and what's returned by &hellip;/datasets and &hellip;/dataset-diff.

How about we don't set `.audit` on `Datasets.createOrMerge`, but instead wait until publishing the form to log `dataset.create` or `dataset.update`? Maybe we could query the dataset diff then to determine whether and what to log.

@sadiqkhoja has made the point that it could be helpful for debugging to log events earlier / more frequently. One idea is that we could add more dataset actions, distinguishing between draft changes to a dataset and published changes to a dataset. It's not clear whether we'd return all those actions over the API or keep some just internal.

**Comment by ktuite** [comment]
This issue is kind of related to this one about listing dataset audit logs via the api: https://github.com/getodk/central-backend/issues/795

**Comment by matthew-white** [comment]
@sadiqkhoja, now that `dataset.update.publish` events are no longer logged, how about we remove that action from the `AuditFiltersAction` component in Frontend?

**Comment by sadiqkhoja** [comment]
@getodk/testers this is ready for testing in staging

**Expected behaviour**

- When you upload a draft form that defines dataset, you won't see any logs on the Systems page
- When you publish that form, you should see a log entry that a new dataset has been created
- When you re-upload a draft form that adds more property in the dataset, you shouldn't see any log, but when you publish this new draft you should see a log entry that the dataset has been updated

**Comment by srujner** [comment]
@sadiqkhoja Should change in the Datasets -> Entity name -> Settings -> Entity Workflow
![Screenshot(153)](https://github.com/getodk/central-backend/assets/85225519/a2c1d1ec-a366-493c-b87a-8c05af985180)
be also visible in the Server Audit Logs?
![Screenshot(154)](https://github.com/getodk/central-backend/assets/85225519/c9628c0a-1ca0-4769-a340-e28e00a0d612)

**Comment by sadiqkhoja** [comment]
yes

**Comment by dbemke** [comment]
If I move a field in a form (I don't add anything) should there be Dataset update event in audit logs?

**Comment by sadiqkhoja** [comment]
no

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by dbemke** [comment]
**Tested with Success!**
