### ISSUE TITLE
Purging forms and submissions that create entities 

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#666]
When a form is purged, it purges the submissions associated with that form. Entities have a `submissionDefId` foreign key that links back to the source submission def, but that foreign key constraint will be violated when the submission is purged. We will change this by allowing the submission def ID to be set to null on the entity. Matt left a comment and example test [here](https://github.com/getodk/central-backend/issues/649#issuecomment-1301611258).

Form purging also affects how the dataset draft endpoints work. Currently, much of the state about a dataset and its properties is inferred from the state of the forms that contribute properties to that dataset. We will add `publishedAt` flags to the datasets themselves and the dataset properties to be a bit more explicit about when properties or whole datasets became available, and rely less on the state of the forms themselves in case they get deleted purged. More notes [here](https://github.com/getodk/central-backend/issues/649#issuecomment-1301627820).

Conceptually, datasets and entities exist in a different realm than forms and submissions. While a form and its submissions get deleted, datasets and entities wont get deleted, though the link between them will be broken. We'll come back to dataset and entity deletion soon.

**Comment by matthew-white** [comment]
I think at some point in the future, we could think about creating submission tombstones, similar to how we save information about a purged form in the `actees` table. A submission tombstone could link to that form actee. We could also think about saving non-sensitive metadata about the submission in the tombstone record, for example, its instance ID.

Especially once a single submission can create multiple submissions, I think it'd be nice to see what the effects of a particular submission were, even after the submission is purged.

That's for the future though! I think we should hold off on implementing something like that until we've thought through the use cases. For now, I think the suggestion above of setting the `submissionDefId` to `null` is a reasonable one. Let me know if you'd like me to file an issue for later about submission tombstones!
