### ISSUE TITLE
Purging Entities and Datasets

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#667]
See this issue #666 for form and submission deletion. We need to handle dataset and entity deletion separately.

**Comment by matthew-white** [comment]
Since this would be a new feature that still needs to be fleshed out, I think we should close this issue and track the feature in the parking lot or future release criteria. This feature would probably require changes to Frontend as well.

**Comment by matthew-white** [comment]
I've made a note of this in the parking lot!
