### ISSUE TITLE
Validate fields saved to dataset properties

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#670]
Comment from [Matt](https://github.com/getodk/central-backend/issues/649#issuecomment-1301597288)

> Should we validate the type of fields that can be used as entity properties? My understanding is that groups and repeat groups are fields that can't be used as entity properties.
> 
> Less sure about this one: for now, should we prohibit any fields within a repeat group from being used as entity properties?
> 
> <hr>
> 
> - check what happens when a structural field is used in a bind that gets picked up by entities 
> - validate and don't allow binds on structural fields if they are for some reason allowed currently
> - don't allow binds on fields within repeat groups
> - keep all this in mind for future versions of entities that use repeats and can make multiple entities per form 

Check what happens when we try to add binds about entity properties to structural fields or fields within repeat groups and don't allow if they don't make sense. 

We'll come back to an updated version of the entity XForm spec that allows for a form to create multiple entities in the future.

**Comment by ktuite** [comment]
Bonus things to test: 
1. try out a form that both produces and consumes a dataset
2. try out a form that tries to have multiple fields bind to the same dataset property

**Comment by matthew-white** [comment]
> try out a form that tries to have multiple fields bind to the same dataset property

I do think we should address this one, as it seems important to the mental model. I also don't think that it'll really work as-is today. If a user really wants to feed multiple fields into a single dataset property, they can do so by combining the fields in a separate `calculate` field, then saving that `calculate` field to the property. I'm [hopeful](https://github.com/getodk/central-backend/pull/576#discussion_r1012205000) that it wouldn't take much to address this, maybe just adjusting a database constraint.

**Comment by matthew-white** [comment]
> - check what happens when a structural field is used in a bind that gets picked up by entities
> - validate and don't allow binds on structural fields if they are for some reason allowed currently

@lognaturel, do you know offhand whether these are possibilities? If not, then I think the only thing we need to do is disallow fields in repeat groups.

**Comment by lognaturel** [comment]
> I do think we should address this one, as it seems important to the mental model. I also don't think that it'll really work as-is today.

I was imagining the last one parsed would win and that would be fine. But maybe that doesn't go well with the way user-specified properties are stored as json?

> validate and don't allow binds on structural fields if they are for some reason allowed currently

`pyxform` will [not allow this](https://github.com/XLSForm/pyxform/pull/624/commits/68708ec1fed9a506983eb2b2af582a6cdeb86127#diff-61e9fd63d6e4bf29ba55beef5eaae1095994e11820ca7c86abce96c880cdc09cR385) and I think that's enough.

> disallow fields in repeat groups

We could do this at the `pyxform` level as well. Depending on what the parsing code does I imagine it will either crash or save every repeat instance (similar to the multiple matching savetos case above).

It feels ok to me to do nothing for 2022.3 and follow up either with a point release or in a later release.

**Comment by matthew-white** [comment]
As long as `pyxform` is doing this validation, it feels OK to leave most of this for later. :+1: Though I see that @ktuite has assigned herself to this issue. @ktuite, how do you think we should prioritize this?

I'd still like to make the following change for v2022.3:

> try out a form that tries to have multiple fields bind to the same dataset property

I think it's important to do that because it involves modifying a database constraint. I think we don't want to have to deal with making that change retroactively. It'll be a super small code change, but I think worth doing.

> I was imagining the last one parsed would win and that would be fine. But maybe that doesn't go well with the way user-specified properties are stored as json?

Hmm that part of the workflow might do what you say and be fine. But I strongly suspect that some SQL joins are assuming that the field:property relationship is 1:1 for a given form def and won't work if it's many:1. I'd be happy to make this change!

**Comment by ktuite** [comment]
I've checked (via editing XML) that if you try to put a "saveto" on a structural field, it ends up as a dataset property but gets ignored in parsing. 

If you bind to something in a repeat group, it picks up the last thing in the group.

I could write tests that show off these specific cases and we can figure out how we really want to handle them later.

**Comment by matthew-white** [comment]
Sounds good! Tests could come later in my opinion.

**Comment by ktuite** [comment]
For release 2023.4, I'm thinking I need to remember what I informally tested before and add real tests.
