### ISSUE TITLE
Attempting to use a form with "fast external itemsets" in a project that has a dataset called itemsets leads to 500

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#673]
Quote from [LN](https://github.com/getodk/central-backend/issues/649#issuecomment-1305057297):

> It feels to me like `itemsets` would be a really strange dataset name so I doubt there would be collisions. `itemsets` is plural because it essentially lets you define multiple datasets that are processed in a custom/magic way by Collect. As @issa-tseng says, there's nothing special about the `itemsets.csv` filename other than IF you're using "fast external itemsets" then that's the name of the CSV that's produced. I don't think it needs to be treated in any special way but it's a good thing to bring up!
> 
> ⚠️ Edit: we should verify the case of a dataset named itemsets.csv and a form that uses “fast external itemsets.” The unusual thing about that feature is that pyxform produces the csv.

**Comment by sadiqkhoja** [comment]
@getodk/testers this can be tested on staging environment

**Comment by srujner** [comment]
Uploading fast-external-itemsets-db-driven.xlsx form on Central took us around 20-30 seconds to create. 
I see there is more than 50k records in the external_choices tab but should it affect the performance in that way?

**Comment by sadiqkhoja** [comment]
Yes, I have observed the same performance, it is dependent on number of rows in `external_choices` tab

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by srujner** [comment]
Tested with success!
