### ISSUE TITLE
Remove "revisionNumber" from datasets

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#674]
Comment from [Matt](https://github.com/getodk/central-backend/issues/649#issuecomment-1308296503):

> I think I'm seeing that simply creating a form draft has the effect of increasing the `revisionNumber` of a dataset. For example:
> 
> - Create a new form that creates entities for a new dataset named `people`. Publish the form. &hellip;/datasets returns `people` with a `revisionNumber` of 0.
> - Create a new draft for the form, but don't publish it. Now &hellip;/datasets returns `people` with a `revisionNumber` of 1.
> - Abandon the draft, then create a new draft. &hellip;/datasets returns `people` with a `revisionNumber` of 2.
> 
> I'd expect that creating but not publishing a form draft wouldn't change an existing dataset in a way that's visible over the API.
> 
> <hr>
> 
> Maybe we could remove `revisionNumber`? Maybe we'd want it in the future, but probably OK to remove for now? For now we could even just remove it from the API (remove `readable` from the field in the frame).

**Comment by matthew-white** [comment]
We can't just remove this field entirely, because we use it here:

https://github.com/getodk/central-backend/blob/d19b72a8f4881218814144dcff229ca0045f2b54/lib/model/query/datasets.js#L147-L150

However, I suspect that #671 may update that code, in which case we may be able to remove the field.

**Comment by sadiqkhoja** [comment]
I have removed `revisionNumber` from projects/:id/datasets API response in #697 . Will remove the column from the table during QA testing period or after release
