### ISSUE TITLE
Guarantee dataset property order in CSV

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#675]
Comment from [Matt](https://github.com/getodk/central-backend/issues/649#issuecomment-1312601181):

> Do we want an `order` column on `ds_properties`? I might be missing something, but right now when we write the entities CSV file, I don't see that there's a guarantee about the order of the columns after `name` and `label` (the order of the properties). I'd expect that the order of the properties would be stable.
> 
> I'm not sure how much the column order matters when the entities CSV file is served to an OpenRosa client. The column order isn't user-facing there, right? But as users start downloading the entities CSV file for use in data management or analysis, I think it'll be important that the column order be stable.
> 
> I don't think we can rely on `form_fields.order` for this, as multiple forms can feed into the dataset: two forms may save the same fields to the same dataset properties, yet have those fields in different relative orders. Even for a single form, the field order may change from version to version. Also, given that forms and datasets are allowed to have separate lifecycles, I think that the order of properties should remain stable even if a contributing form is deleted.
> 
> Instead, I think we should independently track the property order using a column on `ds_properties`. Maybe for now we just order by `ds_properties.id` and have that be our guaranteed order.

**Comment by lognaturel** [comment]
> I'm not sure how much the column order matters when the entities CSV file is served to an OpenRosa client. The column order isn't user-facing there, right?

That's right, it doesn't matter for OpenRosa clients.

> order by ds_properties.id and have that be our guaranteed order.

That feels like a reasonable long term solution to me. We know those ids are auto-incrementing. Why introduce a separate way to capture order?
