### ISSUE TITLE
Don't give access to entity `createdBy` over API.

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#677]
Comment from [Matt](https://github.com/getodk/central-backend/pull/576#discussion_r1012430723):

> I don't think that `createdBy` should be readable over the API except as extended metadata. See 429c77031c3db8df05a66bfb589553357e21d349 and #209.
> 
> Relatedly, I think we could consider the name `actorId` instead of `createdBy`. For example, that's what `comments` has, and `comments` is one of our newest tables.

This seems like a pretty small and straightforward change (though it does require a migration to rename the column).

While we're at it, we could get clear about what a Dataset and an extended metadata dataset looks like, and also add a `Dataset` assertion to test/assertions.js ([comment](https://github.com/getodk/central-backend/pull/576#discussion_r1014981412)).

**Comment by matthew-white** [comment]
Maybe the name `creatorId` would be more descriptive than `actorId`?

I also think it's a little confusing that there are arguably two creators: the user who submitted the submission and the user who approved it. I'm also thinking ahead to a future in which we provide the option to "register on receive". In that case, there will only be one creator: the submitter. Will it be confusing then that `createdBy`/`actorId`/`creatorId` refers to the approver in some cases and the submitter in others?

We don't currently use this property in Frontend, right? How about we leave the `createdBy` field as-is for now, but remove `readable` access to it over the API?

**Comment by lognaturel** [comment]
> createdBy/actorId/creatorId refers to the approver in some cases and the submitter in others

We should only be tracking the submitter ID, I think.

**Comment by matthew-white** [comment]
Oh and it looks like that's what we're doing today. Sorry, I was misunderstanding how this works!

**Comment by matthew-white** [comment]
How about the name `submitterId` then? That's the name we use for submissions.

**Comment by lognaturel** [comment]
> that's what we're doing today

Yay!

> How about the name submitterId

Does that feel right if the entity is created by e.g. a bulk upload?

> leave the createdBy field as-is for now, but remove readable access to it over the API?

Keeping the API minimal sounds really good to me. In this case it would let us clarify what concept we're actually representing before exposing it.

**Comment by matthew-white** [comment]
> > How about the name submitterId
> 
> Does that feel right if the entity is created by e.g. a bulk upload?

Hmm good point, maybe `creatorId` would be better after all.

> Keeping the API minimal sounds really good to me. In this case it would let us clarify what concept we're actually representing before exposing it.

:+1:

I also think that part of the reason I was confused is that right now, the actor of the `entity.create` audit log entry is the approver. I imagine we may need to rethink that once we introduce "register on receive". But the audit log feels like lower stakes / a slightly less stable API, so I also think it's OK to leave it as-is for now.

**Comment by lognaturel** [comment]
I was thinking about this and realized I'm very confused! The conversation about `submitterId` made me think we were discussing an *entity*'s creator. But this is about a *dataset*'s creator, no? I don't see any entity API.

**Comment by matthew-white** [comment]
It's about entities, but like you said, we don't expose entities over the API in this way, so this isn't user-facing at the moment. The issue is that we specify `readable` for `createdBy` in the `Entity` frame. That means that as soon as we start calling `forApi()` on entities, that will include `createdBy` — which I think should be named something else. I'll double-check that `forApi()` isn't called on entities anywhere, but I'm pretty sure it's not. So let's address this later!

**Comment by matthew-white** [comment]
There's a larger issue around how we use `readable` and `writable` in the `Entity` and `Dataset` frames. But a lot of those questions don't end up being user-facing.

**Comment by matthew-white** [comment]
> I'll double-check that `forApi()` isn't called on entities anywhere, but I'm pretty sure it's not.

I realized that it's a little hard to check this, since `forApi()` can be called indirectly by our `serialize()` function. But I diffed `master` with v1.5.3 and searched for `forApi` in the diff and didn't see any relevant `forApi()` calls there. I also defined a `forApi()` method in the `Entity` frame and had it throw an error, then ran tests; no tests failed. All in all, I think this is something we can come back to in v2023.1.

**Comment by ktuite** [comment]
This particular issue is getting addressed by a commit in the odata entity PR #740. It might have been tidier for me to pull it out and put it in its own PR, but since this other one is ready for review, I think I'll leave it as is.

https://github.com/getodk/central-backend/pull/740/commits/91e80575ebb216f372582c36babdae741c4eebbf
