### ISSUE TITLE
Long tail of smaller changes in merged Entities PR

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#678]
There are smaller changes that don't exactly fit into bigger issues that are suggested in the comments for PR #576.

Things like... 

1. Removing `readable`/`writable` from some places in the API where they don't make sense
    * (done in #700)
3. [Clunky code](https://github.com/getodk/central-backend/pull/576#discussion_r1012891214) in the entity CSV streaming that was copied from somewhere else but doesn't apply here 
    * (done in #769 PR that closes this issue)
5. Unnecessary lines of code
    * (probably addressed in #700, otherwise unclear what this refers to)
7. Duplicate tests 
    * (Not sure what this refers to anymore)
9. Etc.

**Comment by sadiqkhoja** [comment]
Created sub-issue to address "before release" items #700. Keeping this issue open and moving it to next release

**Comment by ktuite** [comment]
I've gone through all the comments in https://github.com/getodk/central-backend/pull/576 and it will be safe to close this issue with the linked PR (#769) because everything is either done or in its own issue at this point.
