### ISSUE TITLE
More validation of entity property names

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#688]
We need to do a little more validation of entity property names. pyxform also does that validation, so this issue is for after v2022.3.

What we do today:

- A property cannot be named `name` or `label`.

(Not yet implemented:) We should also require that property names:

- Be valid XML identifiers (start with letter or `_`, can only include letters, numbers, `-`, `_`, `.`)
- Not start with `__`

This is similar to (the same as?) some of the validation that we do today for dataset names.

**Comment by lognaturel** [comment]
> This is similar to (the same as?)

Yes, but it's ok for property names to include periods (part of valid XML identifiers) but not dataset names (so it's easier to have .csv, .zip, etc exports)

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by dbemke** [comment]
**Tested with Success!**
