### ISSUE TITLE
Don't attempt to re-create entity from edited submission

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#729]
On the [forum](https://forum.getodk.org/t/entities-and-datasets-in-odk-central/40051/9), a user ran into an error where they created an entity from a submission, edited the submission hoping to be able to edit the entity, reapproved the submission, and then saw a "Problem creating Entity" error message with no explanation. See [frontend issue](https://github.com/getodk/central-frontend/issues/701) for a fix to make sure this error message is visible.

What is happening is backend is attempting to create an Entity from the re-approved submission, but is running to the entity UUID uniqueness constraint "A resource already exists with uuid value(s) of [some uuid]", and logging this as an `entity.create.error` audit event.

We haven't implemented any entity-updating logic yet, and when we do, we are likely to do it through a different entity-specific editing mechanism, not submission-editing. In the mean time, we shouldn't give the impression that editing a submission *might* work to update an entity. 

In this case where an entity has already been created for this submission, backend shouldn't even try to make another entity and it shouldn't log an error event. The unique UUID error message should only come up if a *separate* submission has a UUID collision with an existing entity. 

Example of this situation on the [QA server](https://test.getodk.cloud/#/projects/422/forms/trees_registration_demo/submissions/uuid%3A8fbd68c9-974a-44b4-8248-4145dd635c26). 
<img width="1147" alt="Screen Shot 2023-01-17 at 10 31 52 AM" src="https://user-images.githubusercontent.com/76205/212983175-66ccb344-7e25-413f-8175-8448d022beb3.png">

**Comment by srujner** [comment]
Tested with Success!

**Comment by dbemke** [comment]
Tested with Success!
