### ISSUE TITLE
`datasets` extended metadata does not match .../datasets count

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#745]
If you request extended metadata for a project, a `datasets` property is returned. However, it looks like that doesn't exclude datasets from form drafts. The &hellip;/datasets endpoint does exclude those datasets, which means that the two endpoints disagree on the number of datasets. That's an issue for Frontend because Frontend uses the `datasets` property to decide whether to render the Datasets tab. Right now, the following sequence is possible:

- Create a new form that creates the first dataset for the project.
- Navigate to the project overview in a new tab (or navigate, then refresh the page). You will see the Datasets tab even though it is supposed to be hidden.
- If you navigate to the Datasets tab, you will be immediately redirected to the homepage. That's because Frontend updates the `datasets` property on the project to match the number of datasets returned by .../datasets, which is 0, causing it to realize that the user shouldn't be on the page after all.

I'm not sure that every aspect of how Frontend works there is ideal, but I do think that we should try to get those two counts in sync.

**Comment by matthew-white** [comment]
I'm going to slot this for 2023.2 unless we have time for it now. Presumably this has been an issue since 2022.3.

**Comment by sadiqkhoja** [comment]
Steps to reproduce:

- Upload a Form that creates a Dataset like tree_registration, but do not publish the form.
- Refresh the page, you will see the Dataset tab
- Click on Dataset tab, you will be redirected to home page

After the fix:
- When you upload the form with Dataset, you should not see the Dataset tab until Form is not published

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by srujner** [comment]
**Tested with success!******
