### ISSUE TITLE
Log correct form action after project is encrypted

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#750]
If managed encryption is enabled for a project, and the project already has a published form, then a new encrypted version of the form is automatically published. Today, we log a `form.update.draft.set` action in the audit log when that takes place (shown in Frontend as Form > Create or Update Draft). However, we should instead log a `form.update.publish` action (shown in Frontend as Form > Publish Draft).

**Comment by srujner** [comment]
Tested with Success!
