### ISSUE TITLE
Prevent select field from being changed to select1

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#758]
Right now, we allow a `select1` field to be changed to a `select` field (a select-multiple) and vice versa. (I think that in XLSForm, `select_one` is an alias for `select1`, and `select_multiple` is an alias for `select`.) We allow such a change because `select1` and `select` fields are both type `string`, and our restrictions around field changes mostly have to do with type.

Conceptually, it seems fine for a `select1` field to be changed to a `select`. In submissions, all `select1` values are valid `select` values. However, the reverse change — changing a `select` field to a `select1` — seems potentially problematic. Not all `select` values are valid `select1` values.

That said, I can't think of anything offhand that would break in Central if a `select` field were changed to a `select1`. Also, even if a user were to change a field from a `select` to a `select1` and something went wrong, they could probably just change the field back to a `select` in a new version. I doubt that changing a `select` field to a `select1` is a common choice. If it were to happen, it could be an issue for downstream tools. Then again, we don't generally validate field values, so maybe downstream tools should just be prepared for unexpected values in general.

@lognaturel and @ktuite, what do you think? Maybe we make this a "help wanted" issue for now? Or perhaps just close?

**Comment by ktuite** [comment]
I could see someone wanting to change the interface between select one and many without changing the underlying path of the field and I don't think we should stop them. 

I can also see the data getting a little messed up (two responses in the same string where only one is expected) but a) it doesn't break anything in central, b) they can change it back to a `select` to get central to separate the responses again, and c) like you said, this sounds like something they could manage in their own tools; it's not going to break an odata export.

**Comment by matthew-white** [comment]
OK, I'll go ahead and close as a "won't fix" then! We can always reopen if need be.
