### ISSUE TITLE
Audit log of Dataset events

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#795]
Add `GET /v1/projects/:projectId/datasets/:name/audits` to show events like `dataset.create`, `dataset.update`, and `dataset.publish` for a given dataset. 

Questions 
- what will frontend need to show?
- what info do we need to store? (will need to probably modify things in model/query/datasets.js)
- this should come after https://github.com/getodk/central-backend/issues/793

**Comment by matthew-white** [comment]
The idea of showing an audit log for an entity list is tracked in the parking lot, so I think we can close out this issue for now. The main thing we need to make progress is a design of what to show in Frontend. Once we know that, we'll know how to set up the Backend endpoint. Once we have release criteria, I think we can open a new issue in the `central` repo.

@ktuite, feel free to reopen if you think it'd be useful to keep this issue open!
