### ISSUE TITLE
Update entity data with PATCH request

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#797]
`PATCH /v1/projects/:projectId/datasets/:name/entities/:uuid`
Can specify updated values for inner data (any property in the dataset) and label in an entity

For this first version, you can send just the data change you want to apply, and we don't enforce any entity versioning (like with the deprecated instance id in submission edits). Version numbers to be figured out in issue #832.

**Comment by issa-tseng** [comment]
by the HTTP spec `PUT` permits creation of a resource but i'm guessing we're not doing that? are we only doing update in general this release, no create?

**Comment by lognaturel** [comment]
I believe that we're only going to do `PATCH` for now per discussion at https://github.com/getodk/central-backend/pull/812/files#r1158006629. Create will be through `POST`, update will be through `PATCH` with either some or all properties provided.
