### ISSUE TITLE
Allow soft-deleting entities

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#803]
We've talked about archiving vs. deleting vs. purging. Archiving is something that could be managed in user-space by adding and editing a specific dataset property so we probably won't directly target that right now. We are aiming to have (soft) entity deletion via the API with this release in order to have full CRUD functionality for entities.

**Comment by matthew-white** [comment]
Soft-deleted entities will continue to be accessible from the API via GET &hellip;/entities?deleted=true.
