### ISSUE TITLE
Refactor Datasets.publishIfExists

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#811]
There's a code complexity that we should try to get rid if: 

`Datasets.createOrMerge` can be called when creating a new form and updating a form. It can create a new dataset or update an existing dataset. It can also publish a dataset or not publish a dataset as its final action. That feels like a 2x2x2 combo of possibilities. Additionally, Datasets can separately be published with `Datasets.publishIfExists`. 

We could simplify this by moving the dataset publishing out of `createOrMerge` and only using `publishIfExists` to publish. This would 
* make it simpler to reason about the flow
* make the SQL easier to maintain
* make it less likely to make mistakes with dataset/dataset property publishing
* simplify the dataset audit logging code (see future issue: https://github.com/getodk/central-backend/issues/795).

Updating and publishing datasets does not need to be extremely performant.

**Comment by matthew-white** [comment]
Closed by #931 I think?
