### ISSUE TITLE
Add update-related properties to entity OData

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#815]
(I don't think I saw this filed elsewhere.) In Frontend, we will display a "Last Updated" timestamp, as well the number of edits (that is, the number of updates to the entity data). We could add those values to the OData `__system` property.

**Comment by lognaturel** [comment]
I believe users will want to see/audit entities that have been manually edited vs. updated by a form being filled out. I think for now we could expose the update count using the word `update` in the property name to give ourselves room to eventually have separate information about edits.

**Comment by matthew-white** [comment]
It'd be nice if the OData filter allowed the user to filter entities on `updatedAt`, since we allow that for submissions. Scripts can filter submissions on `updatedAt` to pull in updates to existing submissions.
