### ISSUE TITLE
Track entity versionNumbers

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#832]
We need some way of tracking versions within an entity as it gets updated. Submissions have a unique instance id for each version and a deprecated id pointing to the previous version. We probably won't do the exact same thing for entities. We do want some way of uniquely identifying versions within an entity. We also need to be able to manage updates from multiple sources including partly offline updates.

**Comment by matthew-white** [comment]
Now that we're doing this in .4, I'll move notes here from the draft release criteria for .5:

**Allow an API update to an Entity to specify a base version**

- Right now, I can make an API update to an Entity by specifying the ?force=true query parameter.
- As an alternative, I should be able to make an API update by specifying the Entity version on top of which my changes should apply.
- If my changes conflict with another update to the Entity, then I should receive a 409 error.
  - Backend might reject for “soft conflicts” (server version has moved forward) too.
