### ISSUE TITLE
deleted form, forms with duplicate titles update properties

### ISSUE THREAD

**Issue by sadiqkhoja** [getodk/central-backend#833]
https://test.getodk.cloud/#/projects/430/datasets/trees - deleted form, forms with duplicate titles update properties

### Steps to reproduce:

- Publish a form that defines a dataset
- Delete that form
- Recreate the same form, you will get a warning that form with same name exists in trash. Upload it anyways
- Publish the form
- Go to the datasets page, select the dataset that's created by the form
- You will see empty rows in front of properties

### Another way to reproduce it:

- Publish a form that defines a dataset
- Create a new draft by clicking "New Draft"
- Publish it as it is, no need to upload any new form definition 
- Go to the datasets page, select the dataset that's created by the form
- You will see empty rows in front of properties

**Comment by dbemke** [comment]
Tested with Success!
