### ISSUE TITLE
meet with ln to discuss offline entities

### ISSUE THREAD

**Issue by sadiqkhoja** [getodk/central-backend#835]

**Comment by lognaturel** [comment]
Any chance a few issues have ended up in the wrong repo, @sadiqkhoja?? I agree we should meet to discuss offline entities,though. 😂 Not sure what IRT is https://github.com/getodk/central-backend/issues/836

**Comment by sadiqkhoja** [comment]
lol, I have started using github project to organize my TODO list and this happened. I should go back to notebook :D

**Comment by sadiqkhoja** [comment]
Can't transfer outside the organization, you can delete these. Sorry about this.
