### ISSUE TITLE
OData: implement $expand

### ISSUE THREAD

**Issue by issa-tseng** [getodk/central-backend#84]
This cannot be done until #82 is resolved, as the thing we would expand we currently omit from our schema declaration.

**Comment by mattelacchiato** [comment]
I'm currently working on this, trying to implement `$expand=*` as discussed here: https://forum.getodk.org/t/extend-api-to-retrieve-plain-json/32204/6?u=mattelacchiato

**Comment by issa-tseng** [comment]
closing this for now since probably most people will be happy w `*`.
