### ISSUE TITLE
Update some entity processing errors to 400.28

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#854]
PR #844 introduces a new Problem `Problem.user.invalidEntity (400.28)` to return when creating an entity from JSON fails because of some formatting or validation problem. New code around JSON entity extraction uses this problem.

Many of the previous validation error cases throw `Problem.user.entityViolation (409.14)`, which is a conflict problem rather than a bad request problem. This problem was made back when we started parsing submission XML to create entities and foresaw entity conflict as one possible problem. 

I think we could go back and update pure validation errors to throw the `400.28` error instead of `409.14`. The names could also be better - `entityConflict` and `invalidEntity` or something.

**Comment by matthew-white** [comment]
I also think we should try to use more specific Problems that already exist when those are appropriate. For example, Problems like `Problem.missingParameter()` or `Problem.invalidDataTypeOfParameter()` that have well-defined detail properties. I think it's nice to have `Problem.invalidEntity()` as a fallback, but I feel like our first choice should be to reach for something more specific.
