### ISSUE TITLE
Create entity without approval

### ISSUE THREAD

**Issue by sadiqkhoja** [getodk/central-backend#864]
Right now, entities are created when someone approves the submission. But for many workflows, this is an inconvenience. 

As a project manager, I should be able to configure whether entities are created on submission receipt or on approval. 

**Release criteria** can be found [here](https://docs.google.com/document/d/1tOBNJaWZSJjkZjTYxV7vYBOFSkiZWKsnp48uWb_L5Co/edit#heading=h.9la51antd6wm).

**Additional details:**
- Configuration flag will be at the Dataset level
- By default, approval will not be required
- Existing datasets will still require approval, user would be able to turn it off
- The flag will be set via API, it cannot be defined in form definition

## Backend:

- [ ] GET /datasets and /dataset/:name should return the current value of the flag
- [ ] PATCH /datasets/:name should update the value of the flag
- [ ] Update entity worker

## Frontend:
- [ ] display the value on list of dataset page
- [ ] have ability to update the value of the flag

**Comment by matthew-white** [comment]
Closed by #868, #870, and getodk/central-frontend#795.

**Comment by srujner** [comment]
Tested with Success!

**Comment by dbemke** [comment]
**Tested with success!**
