### ISSUE TITLE
Usage data is sent a day later than expected

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#921]
I think that we intend to send usage data every 30 days. However, it looks like the data is actually being sent every 31 days.

Relatedly, I've noticed that when I set `default.taskSchedule.analytics` to 1 in the config, usage data is sent every 2 days.

During regression testing, I think it'd be nice if usage data were sent every day so that we could more quickly verify a change to the usage reporting config. @getodk/testers, do you think that would be helpful, or does it not matter much?

For production, if we're currently sending data every 31 days, I don't think we should change that now to every 30 days: I think that would complicate longitudinal analysis.

**Comment by matthew-white** [comment]
> I think that we intend to send usage data every 30 days.

Actually, was 31 intentional? If it were 30, we'd sometimes get multiple reports in a single month.

**Comment by srujner** [comment]
@matthew-white Yes, it would be helpful if during regression testing the usage data was sent every day.
