### ISSUE TITLE
SSO: render simple redirect page rather than copying Frontend styles

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#971]
Continuing the discussion in #910:

- https://github.com/getodk/central-backend/pull/910#discussion_r1310995967
- https://github.com/getodk/central-backend/pull/910#discussion_r1277685758

I suggested there that it'd be better for Backend to render a simple redirect page rather than trying to match Frontend's styles. I think trying to match styles would lead to a maintenance burden as styles change over time. On wider viewports, the current styles don't match on the max width of the panel to an extent that I think would be noticeable to users.

@alxndrsn, let's continue discussing here! Let me know what you think about my most recent comment.

**Comment by matthew-white** [comment]
I brought up this question in a meeting earlier today, and @issa-tseng and @lognaturel offered some thoughts from a design perspective. (I'll try to summarize here, but please correct anything I get wrong.)

- @issa-tseng said that either way would be fine from a design perspective. A bare page wouldn't be a problem. If we do opt for a branded redirect page, the styles should exactly match Frontend.
- @lognaturel also thought that a bare page would be fine.
- Specific idea: Render a bare page with centered text. Use the following text: "Redirecting. Click here if you are not automatically redirected to Central within 5 seconds."
  - @lognaturel said that the text "to Central" could provide branding/continuity for anyone who actually ends up seeing that page for any length of time.
  - One goal is for this text to be short so that users don't feel like they've missed something when the page flashes by.
- Another idea from @issa-tseng: Don't show anything at all on that page at first. After 5 seconds, show some text (using a CSS animation).

@alxndrsn, do any of these ideas seem reasonable to you? There may be other options as well that we haven't considered.

**Comment by lognaturel** [comment]
A quick note that @ktuite brought up and I agree with -- the current page goes by so fast it's hard not to think that something is broken. The advantage of having something really simple like "Redirecting" or "Loading" or a spinner is that it would be understandable in the very short time it's up.

**Comment by alxndrsn** [comment]
Thanks for all the thoughts on this.  

I've opened a PR at https://github.com/getodk/central-backend/pull/981 with the following behaviour:

1. initially: centred animated spinner is displayed

![Screenshot_2023-09-13_11-49-13](https://github.com/getodk/central-backend/assets/191496/c8e85154-a9cc-4cd5-993f-232692857cf1)

2. after 10 seconds: "continue" link fades in below

![Screenshot_2023-09-13_11-49-22](https://github.com/getodk/central-backend/assets/191496/f479f3c8-1b8e-41f1-acfe-c1228fff266b)

Would this be acceptable?

**Comment by matthew-white** [comment]
Just wanted to check about this issue! If it's possible to address this as part of .4, that'd be nice, but I also think it'd be OK to wait until .5. @alxndrsn, what's your current thinking in terms of next steps? I see that you have a PR up that's marked as draft.
