### ISSUE TITLE
Remaining to-dos from SSO PR

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#976]
The SSO PR #910 was merged earlier today. 🎉 This issue is to track comments and any other to-dos from the PR that are still open.

I'm going to copy some to-dos that @alxndrsn mentioned on Slack. @alxndrsn, please feel free to edit or add to the list below! CC also @sadiqkhoja: feel free to leave a comment if there are other to-dos from the PR.

If it'd be helpful, I also think that any of these to-dos could be split into separate issues.

- [x] https://github.com/getodk/central-backend/pull/910#issuecomment-1696768080 - filed at https://github.com/getodk/central-backend/issues/1221
- [x] https://github.com/getodk/central-backend/pull/910#discussion_r1316178821
- [x] https://github.com/getodk/central-backend/pull/910/files#r1311013042
- [x] https://github.com/getodk/central-backend/pull/910/files#r1311024572
- [x] https://github.com/getodk/central-backend/pull/910#discussion_r1311943658

**Moving code around**

- [x] https://github.com/getodk/central-backend/pull/910#discussion_r1310992957 - filed at https://github.com/getodk/central-backend/issues/1222
- [x] https://github.com/getodk/central-backend/pull/910/files#r1310996344

**More in-depth refactor**

- [x] https://github.com/getodk/central-backend/pull/910#discussion_r1311923604 - filed at https://github.com/getodk/central-backend/issues/1223

**Tracked elsewhere**

- https://github.com/getodk/central-backend/pull/910/files#r1310995967 / https://github.com/getodk/central-backend/pull/910#discussion_r1261455506
  - #971

**Comment by matthew-white** [comment]
I can make a note of this in #588, but I thought I'd mention that oidc-e2e-test failed once for me: https://github.com/getodk/central-backend/actions/runs/6218293098/attempts/1. When I reran it, it passed.

**Comment by alxndrsn** [comment]
@matthew-white I've also seen these intermittent failures and in integration tests.  I suspect an issue in the `fake-oidc-server`, but we can't currently see the logs.  I'll see if it's simple to add the logs to the github actions.

**Comment by alxndrsn** [comment]
@matthew-white actually the logs seem to be available already.

From the failure screenshot on your job, it looks like playwright/webkit interaction failure:

![test-failed-1](https://github.com/getodk/central-backend/assets/191496/fd697683-d996-4228-a014-cc8c154d55c6)

It's clear the password has ended up in the wrong input field.

**Comment by alxndrsn** [comment]
There's a very similar bug filed at https://github.com/microsoft/playwright/issues/26349, but without much detail.

**Comment by alxndrsn** [comment]
@matthew-white the other option is to enable retries for the playwright tests.  Less red builds, but also it will mask real problems :shrug:

**Comment by alxndrsn** [comment]
I've opened separate issues for the remaining tasks.
